import { C } from '../shared';

export const aiPanelStyles = {
  aiPanel: { position: 'absolute' as const, top: 66, bottom: 8, left: 8, width: 300, borderRadius: 20, backgroundColor: '#FFFFFF', padding: 18, borderWidth: 1, borderColor: '#E2E8F2', shadowColor: '#AAB4C5', shadowOpacity: 0.18, shadowRadius: 20, shadowOffset: { width: 0, height: 10 }, elevation: 6, zIndex: 20, overflow: 'hidden' as const },
  aiPanelSidebar: { position: 'relative' as const, top: undefined, bottom: undefined, left: undefined, alignSelf: 'stretch' as const, minHeight: 0, height: '100%' as const, borderRadius: 18, zIndex: 10 },
  aiPanelSidebarResizeHandle: { position: 'absolute' as const, top: 0, right: 0, bottom: 0, width: 16, cursor: 'col-resize' as const, zIndex: 130, alignItems: 'center' as const, justifyContent: 'center' as const },
  aiPanelSidebarResizeGrip: { width: 14, minHeight: 38, borderRadius: 99, alignItems: 'center' as const, justifyContent: 'center' as const, gap: 3, backgroundColor: '#EEF2FF', borderWidth: 1, borderColor: '#DCE4FF' },
  aiPanelSidebarResizeDot: { width: 3, height: 3, borderRadius: 99, backgroundColor: '#7A86A3' },
  aiMenuDismissLayer: { position: 'absolute' as const, top: 0, right: 0, bottom: 0, left: 0, zIndex: 50 },
  aiHomePane: { flex: 1, minHeight: 0, zIndex: 60 },
  aiHomePaneShifted: { transform: [{ translateX: 238 }], opacity: 0.46 },
  aiSidebarHomeDismissLayer: { position: 'absolute' as const, top: 0, right: 0, bottom: 0, left: 238, zIndex: 45 },
  aiPanelHeader: { minHeight: 32, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8, paddingRight: 140, marginBottom: 10, position: 'relative' as const, zIndex: 70 },
  aiPanelHeaderDraggable: { cursor: 'move' as const },
  aiHeaderIconButton: { width: 30, height: 30, borderRadius: 8, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#F1F3F6' },
  aiHeaderIconButtonActive: { backgroundColor: '#E8EDFF', borderWidth: 1, borderColor: '#DCE4FF' },
  aiHeaderIconButtonDisabled: { opacity: 0.5 },
  aiHeaderTitleWrap: { flex: 1, minWidth: 0, justifyContent: 'center' as const },
  aiHeaderTitle: { maxWidth: '100%', fontSize: 14, lineHeight: 18, fontWeight: '900' as const, color: '#303744', textAlign: 'left' as const },
  aiHeaderSubtitle: { marginTop: 1, fontSize: 10, lineHeight: 13, fontWeight: '800' as const, color: '#7A8394' },
  aiHeaderModel: { marginTop: 1, maxWidth: '100%', fontSize: 10, lineHeight: 12, fontWeight: '700' as const, color: '#8A93A3', textAlign: 'left' as const },
  aiHeaderActions: { position: 'absolute' as const, right: 0, top: 1, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6 },
  aiHeaderNewChatButton: { height: 30, maxWidth: 68, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 3, borderRadius: 8, backgroundColor: '#F1F3F6', paddingHorizontal: 7 },
  aiHeaderNewChatButtonText: { fontSize: 11, lineHeight: 15, fontWeight: '900' as const, color: '#303744' },
  aiHeaderMenuWrap: { position: 'relative' as const },
  aiHeaderContextMenu: { position: 'absolute' as const, right: 0, top: 36, width: 132, borderRadius: 10, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DEDEDE', paddingVertical: 5, shadowColor: '#000000', shadowOpacity: 0.12, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 12, zIndex: 90 },
  aiHeaderEditRow: { minHeight: 32, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 4, borderRadius: 9, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D7D7D7', paddingHorizontal: 5 },
  aiHeaderEditInput: { flex: 1, minWidth: 0, minHeight: 28, paddingVertical: 0, fontSize: 13, lineHeight: 18, fontWeight: '700' as const, color: '#111827' },
  aiHeaderEditButton: { width: 22, height: 22, borderRadius: 7, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#F0F0F0' },
  aiConversationTitleBar: { minHeight: 34, alignItems: 'center' as const, justifyContent: 'center' as const, paddingHorizontal: 32, marginTop: -4, marginBottom: 4 },
  aiConversationTitle: { maxWidth: '100%', fontSize: 14, lineHeight: 19, fontWeight: '800' as const, color: '#303744', textAlign: 'center' as const },
  aiConversationModel: { marginTop: 1, maxWidth: '100%', fontSize: 10, lineHeight: 13, fontWeight: '700' as const, color: '#8A93A3', textAlign: 'center' as const },
  aiPanelScroll: { flex: 1 },
  aiPanelScrollContent: { paddingBottom: 18 },
  aiPanelClose: { width: 30, height: 30, borderRadius: 99, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#E9EEF6' },
  aiPanelSubtitle: { fontSize: 13, lineHeight: 18, color: '#7E8798', fontWeight: '700' as const, marginBottom: 18 },
  aiChatSidebar: { position: 'absolute' as const, top: 0, bottom: 0, left: 0, width: 238, borderTopLeftRadius: 20, borderBottomLeftRadius: 20, backgroundColor: C.bg, borderRightWidth: 1, borderRightColor: C.line, paddingHorizontal: 8, paddingTop: 18, paddingBottom: 10, zIndex: 80, elevation: 10 },
  aiChatSidebarHeader: { height: 32, flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, marginBottom: 8 },
  aiSidebarCommand: { minHeight: 34, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 9, borderRadius: 9, backgroundColor: '#E8E8E8', paddingHorizontal: 9, marginBottom: 4 },
  aiSidebarCommandText: { fontSize: 13, lineHeight: 18, fontWeight: '700' as const, color: '#111827' },
  aiSidebarSearchRow: { minHeight: 34, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 9, borderRadius: 9, paddingHorizontal: 9, marginBottom: 8 },
  aiSidebarSearchInput: { flex: 1, minHeight: 32, paddingVertical: 0, fontSize: 13, lineHeight: 18, fontWeight: '700' as const, color: '#111827' },
  aiSidebarList: { flex: 1 },
  aiSidebarListContent: { paddingBottom: 18 },
  aiSidebarChatRowWrap: { position: 'relative' as const },
  aiSidebarChatRow: { minHeight: 32, borderRadius: 9, justifyContent: 'center' as const, paddingHorizontal: 8, marginBottom: 3 },
  aiSidebarChatRowActive: { backgroundColor: '#ECECEC' },
  aiSidebarChatContent: { minHeight: 24, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6 },
  aiSidebarChatText: { fontSize: 13, lineHeight: 18, fontWeight: '500' as const, color: '#171717' },
  aiSidebarConnectedBadge: { flexShrink: 0, borderRadius: 999, backgroundColor: '#E8EDFF', paddingHorizontal: 6, paddingVertical: 2, fontSize: 10, lineHeight: 13, fontWeight: '900' as const, color: '#5169D8' },
  aiSidebarEditRow: { minHeight: 36, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 5, borderRadius: 9, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D7D7D7', paddingHorizontal: 6, marginBottom: 3 },
  aiSidebarEditInput: { flex: 1, minWidth: 0, minHeight: 30, paddingVertical: 0, fontSize: 13, lineHeight: 18, fontWeight: '600' as const, color: '#111827' },
  aiSidebarMiniButton: { width: 24, height: 24, borderRadius: 7, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#F0F0F0' },
  aiSidebarContextMenu: { position: 'absolute' as const, right: 4, top: 28, width: 132, borderRadius: 10, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DEDEDE', paddingVertical: 5, shadowColor: '#000000', shadowOpacity: 0.12, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 12, zIndex: 60 },
  aiSidebarContextMenuItem: { minHeight: 32, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 7, paddingHorizontal: 10 },
  aiSidebarContextMenuText: { fontSize: 12, lineHeight: 16, fontWeight: '700' as const, color: '#111827' },
  aiSidebarContextMenuDanger: { color: '#C04B4B' },
  aiRenameModalOverlay: { flex: 1, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: 'rgba(17, 24, 39, 0.34)', padding: 20 },
  aiPanelDialogOverlay: { position: 'absolute' as const, top: 0, right: 0, bottom: 0, left: 0, zIndex: 120, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: 'rgba(17, 24, 39, 0.34)', padding: 14 },
  aiRenameModalCard: { width: '100%', maxWidth: 320, borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E2E8F2', padding: 16, shadowColor: '#000000', shadowOpacity: 0.16, shadowRadius: 18, shadowOffset: { width: 0, height: 10 }, elevation: 14 },
  aiRenameModalTitle: { fontSize: 15, lineHeight: 21, fontWeight: '900' as const, color: '#111827', marginBottom: 12 },
  aiRenameModalBody: { fontSize: 13, lineHeight: 19, fontWeight: '700' as const, color: '#303744' },
  aiRenameModalInput: { minHeight: 42, borderRadius: 10, borderWidth: 1, borderColor: '#D7DDE8', backgroundColor: '#F8FAFC', paddingHorizontal: 12, fontSize: 14, lineHeight: 20, fontWeight: '700' as const, color: '#111827' },
  aiRenameModalInputError: { borderColor: '#C04B4B', backgroundColor: '#FFF7F7' },
  aiRenameModalError: { marginTop: 7, fontSize: 12, lineHeight: 16, fontWeight: '700' as const, color: '#C04B4B' },
  aiRenameModalActions: { flexDirection: 'row' as const, justifyContent: 'flex-end' as const, gap: 8, marginTop: 14 },
  aiRenameModalCancelButton: { minHeight: 34, justifyContent: 'center' as const, borderRadius: 9, backgroundColor: '#EEF2F7', paddingHorizontal: 12 },
  aiRenameModalCancelText: { fontSize: 13, lineHeight: 18, fontWeight: '800' as const, color: '#303744' },
  aiRenameModalSaveButton: { minHeight: 34, justifyContent: 'center' as const, borderRadius: 9, backgroundColor: '#303744', paddingHorizontal: 12 },
  aiRenameModalSaveButtonDisabled: { opacity: 0.45 },
  aiRenameModalDangerButton: { minHeight: 34, justifyContent: 'center' as const, borderRadius: 9, backgroundColor: '#C04B4B', paddingHorizontal: 12 },
  aiRenameModalSaveText: { fontSize: 13, lineHeight: 18, fontWeight: '900' as const, color: '#FFFFFF' },
  aiSidebarEmptyText: { fontSize: 13, lineHeight: 18, color: '#6B7280', fontWeight: '600' as const, paddingHorizontal: 8, paddingVertical: 10 },
  aiConversationShell: { flex: 1, minHeight: 0 },
  aiMessagesScroll: { flex: 1 },
  aiMessagesContent: { flexGrow: 1, justifyContent: 'flex-end' as const, paddingTop: 10, paddingBottom: 12, gap: 10 },
  aiMessageBubble: { maxWidth: '88%', borderRadius: 16, paddingHorizontal: 12, paddingVertical: 10 },
  aiMessageBubbleUser: { alignSelf: 'flex-end' as const, backgroundColor: '#303744' },
  aiMessageBubbleAssistant: { alignSelf: 'stretch' as const, width: '100%' as const, maxWidth: '100%' as const, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E4E9F2' },
  aiMessageAttachmentImage: { width: 150, height: 98, borderRadius: 12, marginBottom: 8, backgroundColor: '#EEF2F7' },
  aiMessageText: { fontSize: 13, lineHeight: 19, fontWeight: '600' as const },
  aiMessageTextUser: { color: '#FFFFFF' },
  aiMessageTextAssistant: { color: '#303744' },
  aiMessagePageLink: { color: '#4F68D2', fontWeight: '900' as const, textDecorationLine: 'underline' as const },
  aiStructuredContent: { alignSelf: 'stretch' as const, width: '100%' as const, gap: 8 },
  aiStructuredParagraph: { marginBottom: 0 },
  aiStructuredSectionCard: { borderRadius: 14, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E8EDF6', paddingHorizontal: 10, paddingVertical: 9, gap: 7 },
  aiStructuredSectionHeader: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 7 },
  aiStructuredSectionIcon: { width: 24, height: 24, borderRadius: 8, backgroundColor: '#EEF2FF', alignItems: 'center' as const, justifyContent: 'center' as const },
  aiStructuredSectionTitle: { flex: 1, minWidth: 0, fontSize: 12, lineHeight: 16, fontWeight: '900' as const, color: '#2F3A4E' },
  aiStructuredSectionBody: { gap: 5 },
  aiStructuredBulletRow: { flexDirection: 'row' as const, alignItems: 'flex-start' as const, gap: 7, marginBottom: 2 },
  aiStructuredBulletDot: { width: 10, fontSize: 13, lineHeight: 19, fontWeight: '900' as const, color: '#5F79FF' },
  aiStructuredBulletText: { flex: 1, minWidth: 0 },
  aiPageRecommendationGroup: { alignSelf: 'stretch' as const, width: '100%' as const, borderRadius: 14, backgroundColor: '#F8FAFF', borderWidth: 1, borderColor: '#E1E8FF', padding: 9, gap: 8 },
  aiPageRecommendationHeader: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 5 },
  aiPageRecommendationTitle: { fontSize: 11, lineHeight: 15, fontWeight: '900' as const, color: '#4F68D2' },
  aiPageRecommendationList: { alignSelf: 'stretch' as const, width: '100%' as const, gap: 6 },
  aiPageRecommendationItem: { alignSelf: 'stretch' as const, width: '100%' as const, minHeight: 40, borderRadius: 12, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E8EDF8', paddingHorizontal: 8, paddingVertical: 7, flexDirection: 'row' as const, alignItems: 'flex-start' as const, gap: 8 },
  aiPageRecommendationPill: { minWidth: 38, height: 26, borderRadius: 999, backgroundColor: '#EEF2FF', alignItems: 'center' as const, justifyContent: 'center' as const, paddingHorizontal: 8 },
  aiPageRecommendationPillText: { fontSize: 11, lineHeight: 14, fontWeight: '900' as const, color: '#4F68D2' },
  aiPageRecommendationBody: { flex: 1, minWidth: 0, fontSize: 12, lineHeight: 17, fontWeight: '800' as const, color: '#303744' },
  aiEmptyConversation: { flex: 1, alignItems: 'center' as const, justifyContent: 'center' as const, paddingHorizontal: 12 },
  aiEmptyConversationTitle: { fontSize: 18, lineHeight: 24, fontWeight: '800' as const, color: '#303744', textAlign: 'center' as const, marginBottom: 6 },
  aiEmptyConversationBody: { fontSize: 13, lineHeight: 19, fontWeight: '600' as const, color: '#737B88', textAlign: 'center' as const },
  aiComposer: { borderTopWidth: 1, borderTopColor: '#E6EAF2', paddingTop: 10 },
  aiReadOnlyNotice: { minHeight: 34, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 7, borderRadius: 11, backgroundColor: '#F3F6FC', borderWidth: 1, borderColor: '#E0E6F0', paddingHorizontal: 10, paddingVertical: 7, marginBottom: 8 },
  aiReadOnlyNoticeText: { flex: 1, minWidth: 0, fontSize: 12, lineHeight: 16, fontWeight: '800' as const, color: '#5B6472' },
  aiReadOnlyReturnButton: { flexShrink: 0, minHeight: 26, justifyContent: 'center' as const, borderRadius: 8, backgroundColor: '#303744', paddingHorizontal: 9 },
  aiReadOnlyReturnText: { fontSize: 11, lineHeight: 15, fontWeight: '900' as const, color: '#FFFFFF' },
  aiSelectionAttachment: { alignSelf: 'flex-start' as const, width: 78, height: 58, marginBottom: 8, overflow: 'visible' as const, position: 'relative' as const },
  aiSelectionAttachmentImage: { width: '100%', height: '100%', borderRadius: 9 },
  aiSelectionAttachmentFallback: { width: '100%', height: '100%', borderRadius: 9, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#EEF2FF' },
  aiSelectionAttachmentRemove: { position: 'absolute' as const, top: -6, right: -6, width: 20, height: 20, borderRadius: 10, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#303744', borderWidth: 1, borderColor: '#FFFFFF' },
  aiComposerQuickRow: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: 7, marginBottom: 8 },
  aiComposerQuickChip: { minHeight: 30, borderRadius: 999, backgroundColor: '#F5F7FE', borderWidth: 1, borderColor: '#DCE5FF', alignItems: 'center' as const, justifyContent: 'center' as const, paddingHorizontal: 10 },
  aiComposerQuickChipText: { fontSize: 11, lineHeight: 15, fontWeight: '900' as const, color: '#4F68D2' },
  aiClassInsightStrip: { borderRadius: 14, backgroundColor: '#F7F9FF', borderWidth: 1, borderColor: '#E1E7FF', padding: 10, marginBottom: 8 },
  aiClassInsightHeader: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, gap: 8, marginBottom: 8 },
  aiClassInsightTitle: { fontSize: 12, lineHeight: 16, fontWeight: '900' as const, color: '#303744' },
  aiClassInsightMeta: { flexShrink: 1, fontSize: 10, lineHeight: 14, fontWeight: '800' as const, color: '#7B86A0', textAlign: 'right' as const },
  aiClassInsightChipRow: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: 7 },
  aiClassInsightChip: { minHeight: 34, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6, borderRadius: 999, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DCE4FF', paddingHorizontal: 10 },
  aiClassInsightPage: { fontSize: 12, lineHeight: 16, fontWeight: '900' as const, color: '#4F68D2' },
  aiClassInsightPriority: { fontSize: 10, lineHeight: 14, fontWeight: '900' as const, color: '#6B7280' },
  aiComposerInputShell: { minHeight: 52, flexDirection: 'row' as const, alignItems: 'flex-end' as const, gap: 8, borderRadius: 18, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DDE3EC', paddingHorizontal: 12, paddingVertical: 9 },
  aiComposerInput: { flex: 1, maxHeight: 120, minHeight: 34, paddingVertical: 6, fontSize: 14, lineHeight: 20, fontWeight: '600' as const, color: '#303744', textAlignVertical: 'top' as const },
  aiSendButton: { width: 34, height: 34, borderRadius: 99, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#303744' },
  aiSendButtonDisabled: { opacity: 0.45 },
  aiChatHeaderRow: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, marginBottom: 8 },
  aiNewChatButton: { minHeight: 30, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 4, borderRadius: 10, backgroundColor: '#EEF2FF', borderWidth: 1, borderColor: '#DCE4FF', paddingHorizontal: 9 },
  aiNewChatButtonText: { fontSize: 12, lineHeight: 16, fontWeight: '900' as const, color: '#5169D8' },
  aiChatScopeTabs: { flexDirection: 'row' as const, gap: 6, marginBottom: 10 },
  aiChatScopeTab: { flex: 1, minHeight: 34, borderRadius: 11, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E4E9F2', alignItems: 'center' as const, justifyContent: 'center' as const, paddingHorizontal: 8 },
  aiChatScopeTabActive: { backgroundColor: '#EEF2FF', borderColor: '#C9D5FF' },
  aiChatScopeTabText: { fontSize: 11, lineHeight: 15, fontWeight: '900' as const, color: '#7A8394', textAlign: 'center' as const },
  aiChatScopeTabTextActive: { color: '#405CD1' },
  aiChatSearchShell: { minHeight: 38, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8, borderRadius: 12, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E4E9F2', paddingHorizontal: 10, marginBottom: 10 },
  aiChatSearchInput: { flex: 1, minHeight: 36, fontSize: 13, lineHeight: 18, fontWeight: '700' as const, color: '#31405B', paddingVertical: 0 },
  aiChatSearchClear: { width: 24, height: 24, borderRadius: 99, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#F1F4F9' },
  aiChatList: { gap: 8, marginBottom: 16 },
  aiChatListItem: { minHeight: 50, borderRadius: 14, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E4E9F2', paddingHorizontal: 12, paddingVertical: 8, justifyContent: 'center' as const },
  aiChatListItemActive: { backgroundColor: '#EEF2FF', borderColor: '#C9D5FF' },
  aiChatListItemRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8 },
  aiChatListItemMain: { flex: 1, minWidth: 0 },
  aiChatListItemActions: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6 },
  aiChatListItemTitle: { fontSize: 13, lineHeight: 18, fontWeight: '800' as const, color: '#31405B' },
  aiChatListItemTitleActive: { color: '#405CD1' },
  aiChatListItemMeta: { marginTop: 2, fontSize: 11, lineHeight: 14, fontWeight: '700' as const, color: '#8A93A3' },
  aiChatIconButton: { width: 28, height: 28, borderRadius: 9, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#F4F6FB', borderWidth: 1, borderColor: '#E5EAF3' },
  aiChatEditRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6 },
  aiChatEditInput: { flex: 1, minWidth: 0, minHeight: 32, borderRadius: 10, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#CAD6FF', paddingHorizontal: 9, paddingVertical: 0, fontSize: 13, lineHeight: 18, fontWeight: '800' as const, color: '#31405B' },
  aiEmptyChatButton: { minHeight: 42, borderRadius: 14, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E4E9F2', alignItems: 'center' as const, justifyContent: 'center' as const, marginBottom: 16 },
  aiEmptyChatButtonText: { fontSize: 13, fontWeight: '900' as const, color: '#5169D8' },
  aiStateCard: { borderRadius: 16, backgroundColor: '#FFFFFF', padding: 14, marginBottom: 16, borderWidth: 1, borderColor: '#E4E9F2' },
  aiStateTitle: { fontSize: 12, fontWeight: '800' as const, color: '#8D96A6', marginBottom: 8 },
  aiStateBody: { fontSize: 14, lineHeight: 20, color: '#243047', fontWeight: '700' as const },
  aiSectionLabel: { fontSize: 11, fontWeight: '800' as const, color: '#8A93A3', marginBottom: 8 },
  aiSuggestionChip: { borderRadius: 14, borderWidth: 1, borderColor: '#E4E9F2', backgroundColor: '#FFFFFF', paddingHorizontal: 12, paddingVertical: 10, marginBottom: 8 },
  aiSuggestionText: { fontSize: 13, lineHeight: 18, color: '#31405B', fontWeight: '700' as const },
  aiInputShell: { borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E4E9F2', paddingHorizontal: 12, paddingVertical: 10, marginBottom: 16 },
  aiInput: { minHeight: 96, color: '#243047', fontSize: 14, lineHeight: 20, fontWeight: '600' as const, textAlignVertical: 'top' as const },
  aiActionRow: { flexDirection: 'row' as const, gap: 8, marginBottom: 12 },
  aiPrimaryButton: { flex: 1, minHeight: 38, borderRadius: 12, backgroundColor: '#5F79FF', alignItems: 'center' as const, justifyContent: 'center' as const, paddingHorizontal: 12 },
  aiPrimaryButtonText: { fontSize: 13, fontWeight: '900' as const, color: '#FFFFFF' },
  aiSecondaryButton: { flex: 1, minHeight: 38, borderRadius: 12, backgroundColor: '#EEF2FF', borderWidth: 1, borderColor: '#DCE4FF', alignItems: 'center' as const, justifyContent: 'center' as const, paddingHorizontal: 12 },
  aiSecondaryButtonDisabled: { backgroundColor: '#F5F7FB', borderColor: '#E8ECF4' },
  aiSecondaryButtonText: { fontSize: 12, lineHeight: 16, fontWeight: '900' as const, color: '#5169D8', textAlign: 'center' as const },
  aiSecondaryButtonTextDisabled: { color: '#A8B0BF' },
  aiErrorText: { fontSize: 12, lineHeight: 17, fontWeight: '700' as const, color: '#C35A5A', marginBottom: 12 },
  aiResponseCard: { borderRadius: 16, backgroundColor: '#FFFFFF', padding: 14, borderWidth: 1, borderColor: '#E4E9F2' },
  aiResponseTitle: { fontSize: 12, fontWeight: '800' as const, color: '#8D96A6', marginBottom: 8 },
  aiQuestionPill: { alignSelf: 'flex-start' as const, borderRadius: 999, backgroundColor: '#F3F6FC', borderWidth: 1, borderColor: '#E3E9F4', paddingHorizontal: 10, paddingVertical: 6, marginBottom: 10 },
  aiQuestionPillText: { fontSize: 12, lineHeight: 16, color: '#4E5C76', fontWeight: '700' as const },
  aiResponseSection: { marginBottom: 14 },
  aiResponseSectionLast: { marginBottom: 0 },
  aiResponseSectionTitle: { fontSize: 15, lineHeight: 20, color: '#2F3A4E', fontWeight: '800' as const, marginBottom: 6 },
  aiResponseBody: { fontSize: 13, lineHeight: 19, color: '#42506A', fontWeight: '600' as const },
  aiResponsePageLink: { color: '#4F68D2', fontWeight: '900' as const, textDecorationLine: 'underline' as const },
};

export const aiCanvasStyles = {
  aiIconButton: { backgroundColor: '#F7F8FE', borderColor: '#E7EBFA' },
  aiIconButtonActive: { backgroundColor: '#EEF1FD', borderColor: '#D8E0FB' },
  aiCanvasToolbarButton: { backgroundColor: '#F7F9FE', borderColor: '#E4EAF8' },
  aiCanvasToolbarButtonActive: { backgroundColor: '#EEF1FD', borderColor: '#D8E0FB' },
  aiCanvasPanel: { width: 360, alignSelf: 'stretch' as const, minHeight: 0, borderRadius: 18, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E2E8F2', padding: 14, shadowColor: '#AAB4C5', shadowOpacity: 0.12, shadowRadius: 14, shadowOffset: { width: 0, height: 8 }, elevation: 4 },
  aiCanvasHeader: { minHeight: 38, flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, gap: 10, marginBottom: 12 },
  aiCanvasHeaderTitleWrap: { flex: 1, minWidth: 0, position: 'relative' as const },
  aiCanvasEyebrow: { fontSize: 10, lineHeight: 14, fontWeight: '900' as const, letterSpacing: 0.7, color: '#8E99AB', marginBottom: 2 },
  aiCanvasTitleRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 4 },
  aiCanvasTitleButton: { flex: 1, minWidth: 0, minHeight: 24, justifyContent: 'center' as const },
  aiCanvasTitle: { fontSize: 16, lineHeight: 21, fontWeight: '900' as const, color: '#243247' },
  aiCanvasDropdownButton: { width: 26, height: 26, borderRadius: 8, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#F4F6FB', borderWidth: 1, borderColor: '#E5EAF3' },
  aiCanvasTitleMenu: { position: 'absolute' as const, top: 40, left: 0, zIndex: 20, minWidth: 136, borderRadius: 12, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E1E7F0', paddingVertical: 5, shadowColor: '#AAB4C5', shadowOpacity: 0.18, shadowRadius: 12, shadowOffset: { width: 0, height: 8 }, elevation: 8 },
  aiCanvasTitleMenuItem: { minHeight: 34, justifyContent: 'center' as const, paddingHorizontal: 12 },
  aiCanvasTitleMenuText: { fontSize: 12, lineHeight: 16, fontWeight: '900' as const, color: '#303744' },
  aiCanvasTitleMenuDangerText: { fontSize: 12, lineHeight: 16, fontWeight: '900' as const, color: '#C04B4B' },
  aiCanvasHeaderActions: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8 },
  aiCanvasHeaderNewButton: { minHeight: 32, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 5, borderRadius: 10, backgroundColor: '#303744', paddingHorizontal: 10 },
  aiCanvasHeaderNewButtonText: { fontSize: 12, lineHeight: 16, fontWeight: '900' as const, color: '#FFFFFF' },
  aiCanvasIconButton: { width: 32, height: 32, borderRadius: 10, backgroundColor: '#F4F6FB', borderWidth: 1, borderColor: '#E5EAF3', alignItems: 'center' as const, justifyContent: 'center' as const },
  aiCanvasToolbar: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8, marginBottom: 10 },
  aiCanvasPrimaryButton: { minHeight: 34, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 5, borderRadius: 11, backgroundColor: '#303744', paddingHorizontal: 11 },
  aiCanvasPrimaryButtonText: { fontSize: 12, lineHeight: 16, fontWeight: '900' as const, color: '#FFFFFF' },
  aiCanvasLimitText: { fontSize: 11, lineHeight: 14, fontWeight: '900' as const, color: '#8A95A8' },
  aiCanvasModeTabs: { flex: 1, minWidth: 0, flexDirection: 'row' as const, borderRadius: 11, backgroundColor: '#F3F6FB', padding: 3 },
  aiCanvasModeTab: { flex: 1, minHeight: 28, borderRadius: 8, alignItems: 'center' as const, justifyContent: 'center' as const },
  aiCanvasModeTabActive: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E2E8F2' },
  aiCanvasModeTabText: { fontSize: 11, lineHeight: 15, fontWeight: '900' as const, color: '#8B96A9' },
  aiCanvasModeTabTextActive: { color: '#405CD1' },
  aiCanvasLoading: { minHeight: 36, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8, marginBottom: 8 },
  aiCanvasErrorText: { fontSize: 12, lineHeight: 17, fontWeight: '800' as const, color: '#C35A5A', marginBottom: 8 },
  aiCanvasNoteTabs: { flexGrow: 0, marginBottom: 10 },
  aiCanvasNoteTabsContent: { gap: 7, paddingRight: 4 },
  aiCanvasNoteTab: { maxWidth: 160, minHeight: 32, borderRadius: 11, backgroundColor: '#F7F9FC', borderWidth: 1, borderColor: '#E7ECF4', paddingHorizontal: 10, alignItems: 'center' as const, justifyContent: 'center' as const },
  aiCanvasNoteTabActive: { backgroundColor: '#EEF2FF', borderColor: '#C9D5FF' },
  aiCanvasNoteTabText: { fontSize: 12, lineHeight: 16, fontWeight: '800' as const, color: '#667184' },
  aiCanvasNoteTabTextActive: { color: '#405CD1' },
  aiCanvasEditorShell: { flex: 1, minHeight: 0 },
  aiCanvasEditorScroll: { flex: 1, minHeight: 0 },
  aiCanvasEditorContent: { paddingBottom: 12 },
  aiCanvasMarkdownInput: { minHeight: 220, borderRadius: 14, backgroundColor: '#F8FAFD', borderWidth: 1, borderColor: '#E7ECF4', paddingHorizontal: 12, paddingVertical: 12, fontSize: 13, lineHeight: 20, fontWeight: '700' as const, color: '#263144' },
  aiCanvasPreviewScroll: { flex: 1, minHeight: 0, borderRadius: 14, backgroundColor: '#FFFEFC', borderWidth: 1, borderColor: '#E7ECF4' },
  aiCanvasPreviewBox: { minHeight: 220, borderRadius: 14, backgroundColor: '#FFFEFC', borderWidth: 1, borderColor: '#E7ECF4', paddingHorizontal: 14, paddingVertical: 14 },
  aiCanvasPreviewContent: { paddingHorizontal: 14, paddingVertical: 14, paddingBottom: 24 },
  aiCanvasMarkdown: { gap: 4 },
  aiCanvasMarkdownSpacer: { height: 8 },
  aiCanvasHeading1: { fontSize: 20, lineHeight: 27, fontWeight: '900' as const, color: '#1F2937', marginBottom: 8 },
  aiCanvasHeading2: { fontSize: 17, lineHeight: 24, fontWeight: '900' as const, color: '#263144', marginTop: 6, marginBottom: 6 },
  aiCanvasHeading3: { fontSize: 15, lineHeight: 22, fontWeight: '900' as const, color: '#31405B', marginTop: 4, marginBottom: 4 },
  aiCanvasParagraph: { flex: 1, minWidth: 0, fontSize: 13, lineHeight: 20, fontWeight: '700' as const, color: '#445066' },
  aiCanvasListRow: { flexDirection: 'row' as const, alignItems: 'flex-start' as const, gap: 7, marginBottom: 3 },
  aiCanvasListBullet: { width: 12, fontSize: 13, lineHeight: 20, fontWeight: '900' as const, color: '#5F79FF' },
  aiCanvasListNumber: { width: 22, fontSize: 13, lineHeight: 20, fontWeight: '900' as const, color: '#5F79FF' },
  aiCanvasFooter: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, gap: 8, marginTop: 10 },
  aiCanvasAiEditTitle: { fontSize: 12, lineHeight: 16, fontWeight: '900' as const, color: '#31405B' },
  aiCanvasAiDraftCard: { maxHeight: 270, borderRadius: 14, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#C9D5FF', padding: 10, marginTop: 10 },
  aiCanvasAiDraftPreview: { flexGrow: 0, maxHeight: 170, borderRadius: 12, backgroundColor: '#FFFEFC', borderWidth: 1, borderColor: '#E7ECF4', marginTop: 8 },
  aiCanvasDeleteButton: { minHeight: 34, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 5, borderRadius: 11, backgroundColor: '#FFF1F1', borderWidth: 1, borderColor: '#FFD8D8', paddingHorizontal: 11 },
  aiCanvasDeleteButtonText: { fontSize: 12, lineHeight: 16, fontWeight: '900' as const, color: '#C04B4B' },
  aiCanvasSaveButton: { minWidth: 74, minHeight: 34, borderRadius: 11, backgroundColor: '#5F79FF', alignItems: 'center' as const, justifyContent: 'center' as const, paddingHorizontal: 12 },
  aiCanvasSaveButtonDisabled: { opacity: 0.45 },
  aiCanvasSaveButtonText: { fontSize: 12, lineHeight: 16, fontWeight: '900' as const, color: '#FFFFFF' },
  aiCanvasStateCard: { borderRadius: 16, backgroundColor: '#F8FAFD', borderWidth: 1, borderColor: '#E7ECF4', padding: 16, gap: 8 },
  aiCanvasStateTitle: { fontSize: 14, lineHeight: 19, fontWeight: '900' as const, color: '#303A4C' },
  aiCanvasStateBody: { fontSize: 12, lineHeight: 18, fontWeight: '700' as const, color: '#7A8394' },
};
