import { C } from './shared';

export const captureStyles = {
  currentClassCard: { backgroundColor: C.blueSoft, borderRadius: 14, padding: 16, marginBottom: 16, borderWidth: 1, borderColor: '#DDE3FF' },
  currentClassBadge: { flexDirection: 'row' as const, alignItems: 'center' as const, marginBottom: 10 },
  currentClassBadgeIcon: { color: C.blue, fontSize: 12, marginRight: 6 },
  currentClassBadgeText: { fontSize: 12, fontWeight: '800' as const, color: C.blue },
  currentClassTitle: { fontSize: 17, fontWeight: '800' as const, color: C.text, marginBottom: 6 },
  currentClassText: { fontSize: 13, lineHeight: 18, color: '#98A0AF', fontWeight: '600' as const },
  fieldLabel: { fontSize: 12, fontWeight: '700' as const, color: '#9CA4B2', marginBottom: 8 },
  selectBox: { minHeight: 46, borderRadius: 12, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#ECEEF5', paddingHorizontal: 14, flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const },
  selectBoxOpen: { borderBottomLeftRadius: 0, borderBottomRightRadius: 0 },
  selectText: { fontSize: 15, fontWeight: '700' as const, color: C.text },
  selectArrow: { fontSize: 18, color: '#8F96A5' },
  dropdown: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#ECEEF5', borderTopWidth: 0, borderBottomLeftRadius: 12, borderBottomRightRadius: 12, overflow: 'hidden' as const, marginBottom: 18 },
  dropdownRow: { minHeight: 52, paddingHorizontal: 16, justifyContent: 'center' as const, backgroundColor: '#FFFFFF' },
  dropdownRowActive: { backgroundColor: '#EEF1FF' },
  dropdownText: { fontSize: 15, fontWeight: '700' as const, color: '#373E4C' },
  dropdownTextActive: { color: C.blue },
  captureActions: { marginTop: 24 },
  primaryButton: { height: 50, borderRadius: 10, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: C.blue, marginBottom: 12 },
  primaryButtonText: { color: '#FFF', fontSize: 16, fontWeight: '800' as const },
  secondaryButton: { height: 50, borderRadius: 10, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#ECEEF5', marginBottom: 12 },
  secondaryButtonText: { color: '#2F3644', fontSize: 16, fontWeight: '700' as const },
  tertiaryButton: { height: 46, borderRadius: 10, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#F5F7FB', borderWidth: 1, borderColor: '#E3E7EF' },
  tertiaryButtonText: { color: '#526076', fontSize: 14, fontWeight: '800' as const },
  captureMockCard: { marginTop: 18, borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E5EAF3', padding: 16 },
  captureMockTitle: { fontSize: 15, fontWeight: '800' as const, color: C.text, marginBottom: 8 },
  captureMockBody: { fontSize: 13, lineHeight: 18, color: '#7D8797', fontWeight: '600' as const, marginBottom: 14 },
  capturePendingText: { fontSize: 12, fontWeight: '800' as const, color: C.blue, marginTop: 2 },
  captureFeedbackText: { fontSize: 12, lineHeight: 17, color: '#4E72DD', fontWeight: '700' as const, marginTop: 8 },
  captureErrorText: { fontSize: 12, lineHeight: 17, color: '#C04B4B', fontWeight: '700' as const, marginTop: 8 },
  captureRecentCard: { marginTop: 18, borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E5EAF3', padding: 16 },
  captureRecentTitle: { fontSize: 15, fontWeight: '800' as const, color: C.text, marginBottom: 8 },
  captureRecentRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 12, paddingVertical: 10, borderTopWidth: 1, borderTopColor: '#EEF2F6' },
  captureRecentRowFirst: { borderTopWidth: 0, paddingTop: 6 },
  captureRecentMeta: { flex: 1 },
  captureRecentType: { fontSize: 10, fontWeight: '900' as const, color: '#8792A6', letterSpacing: 0.6, marginBottom: 6 },
  captureRecentName: { fontSize: 14, lineHeight: 18, color: '#293244', fontWeight: '800' as const, marginBottom: 4 },
  captureRecentTime: { fontSize: 12, color: '#7D8797', fontWeight: '600' as const },
  captureRecentStatusPill: { height: 28, paddingHorizontal: 10, borderRadius: 999, backgroundColor: '#EEF5FF', alignItems: 'center' as const, justifyContent: 'center' as const },
  captureRecentStatusText: { fontSize: 11, fontWeight: '800' as const, color: '#4E72DD' },
  captureEmptyCard: { marginTop: 18, borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E5EAF3', padding: 16 },
  captureEmptyTitle: { fontSize: 14, fontWeight: '800' as const, color: '#334055', marginBottom: 6 },
  captureEmptyBody: { fontSize: 12, lineHeight: 18, color: '#7D8797', fontWeight: '600' as const },
  captureHint: { textAlign: 'center' as const, marginTop: 18, color: '#D0D4DD', fontSize: 11, fontWeight: '600' as const },

  cameraScreen: { flex: 1, backgroundColor: '#000', paddingTop: 8, paddingHorizontal: 14 },
  cameraTopRow: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, marginBottom: 10 },
  cameraTopButton: { width: 32, height: 32, alignItems: 'center' as const, justifyContent: 'center' as const },
  cameraTopButtonText: { color: '#FFF', fontSize: 22, fontWeight: '600' as const },
  cameraSubject: { color: '#FFF', fontSize: 15, fontWeight: '800' as const },
  cameraGuideLabel: { color: '#FFF', textAlign: 'center' as const, fontSize: 13, fontWeight: '700' as const, marginBottom: 20 },
  cameraStage: { flex: 1, alignItems: 'center' as const, justifyContent: 'center' as const },
  scanFrame: { width: '84%', aspectRatio: 0.78, borderRadius: 12, position: 'relative' as const },
  corner: { position: 'absolute' as const, width: 24, height: 24, borderColor: '#FFF' },
  cornerTL: { top: 0, left: 0, borderTopWidth: 4, borderLeftWidth: 4, borderTopLeftRadius: 12 },
  cornerTR: { top: 0, right: 0, borderTopWidth: 4, borderRightWidth: 4, borderTopRightRadius: 12 },
  cornerBL: { bottom: 0, left: 0, borderBottomWidth: 4, borderLeftWidth: 4, borderBottomLeftRadius: 12 },
  cornerBR: { bottom: 0, right: 0, borderBottomWidth: 4, borderRightWidth: 4, borderBottomRightRadius: 12 },
  zoomBar: { alignSelf: 'center' as const, flexDirection: 'row' as const, backgroundColor: '#101010', borderRadius: 999, padding: 4, marginBottom: 22 },
  zoomPill: { paddingHorizontal: 14, height: 30, borderRadius: 999, alignItems: 'center' as const, justifyContent: 'center' as const },
  zoomPillActive: { backgroundColor: '#FFF' },
  zoomText: { color: '#8F8F8F', fontSize: 14, fontWeight: '800' as const },
  zoomTextActive: { color: '#000' },
  cameraBottomRow: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, paddingHorizontal: 18, paddingBottom: 26 },
  galleryMini: { width: 40, height: 40, borderRadius: 8, backgroundColor: '#262626', alignItems: 'center' as const, justifyContent: 'center' as const, borderWidth: 1, borderColor: '#4B4B4B' },
  galleryMiniText: { fontSize: 18 },
  shutterOuter: { width: 74, height: 74, borderRadius: 99, backgroundColor: '#FFF', alignItems: 'center' as const, justifyContent: 'center' as const },
  shutterInner: { width: 62, height: 62, borderRadius: 99, borderWidth: 2, borderColor: '#8A8A8A' },
  cameraBottomSpacer: { width: 40 },

  desktopCaptureLayout: { flexDirection: 'row' as const, gap: 24, alignItems: 'stretch' as const },
  desktopCaptureLayoutCompact: { gap: 18 },
  desktopCameraMock: { flex: 1, backgroundColor: '#000', borderRadius: 24, minHeight: 680, alignItems: 'center' as const, justifyContent: 'center' as const },
  desktopCameraMockCompact: { borderRadius: 20 },
  desktopCaptureSide: { width: 340 },
  desktopCaptureSideCompact: { width: 300 },
  currentClassCardCompact: { marginBottom: 12 },
  desktopSubjectPickerRow: { borderRadius: 14, borderWidth: 1, borderColor: '#ECEEF5', marginBottom: 10 },
  desktopCaptureForm: { width: '100%', maxWidth: 1180 },
  desktopCaptureFormCompact: { maxWidth: '100%' },
  desktopDropdown: { marginBottom: 12 },
  desktopCaptureActions: { marginTop: 10 },
  webCaptureGrid: { maxWidth: '100%', backgroundColor: '#FFFFFF', borderRadius: 24, borderWidth: 1, borderColor: '#DDE5EF', padding: 22 },
};
