import { StyleSheet } from 'react-native';
import { C } from './shared';

export const notesStyles = {
  subjectRow: { flexDirection: 'row' as const, alignItems: 'center' as const, paddingHorizontal: 16, minHeight: 84, borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#EEF1F6', marginBottom: 12 },
  subjectRowActive: { shadowOpacity: 0.12, shadowRadius: 18, shadowOffset: { width: 0, height: 8 }, elevation: 4 },
  subjectIconBox: { width: 46, height: 46, borderRadius: 12, alignItems: 'center' as const, justifyContent: 'center' as const, marginRight: 14 },
  subjectDot: { width: 12, height: 12, borderRadius: 99 },
  subjectTitle: { fontSize: 17, fontWeight: '800' as const, color: C.text, marginBottom: 5, letterSpacing: 0 },
  subjectTitleActive: { color: '#222938' },
  subjectMeta: { fontSize: 14, color: '#9AA1AF', fontWeight: '700' as const },
  subjectMetaActive: { color: '#5E6675' },
  subjectHeroCard: { flexDirection: 'row' as const, alignItems: 'center' as const, borderWidth: 1, borderRadius: 14, paddingHorizontal: 14, paddingVertical: 14, marginBottom: 12 },
  subjectHeroDot: { width: 12, height: 12, borderRadius: 99, marginRight: 12 },
  subjectHeroTitle: { fontSize: 15, fontWeight: '800' as const, marginBottom: 4 },
  subjectHeroMeta: { fontSize: 12, lineHeight: 17, opacity: 0.84, fontWeight: '700' as const },

  noteListCard: { flexDirection: 'row' as const, alignItems: 'center' as const, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#ECEEF5', borderRadius: 18, paddingHorizontal: 14, paddingVertical: 14, marginBottom: 14, minHeight: 92 },
  noteListRail: { width: 5, height: 60, borderRadius: 99, marginRight: 12 },
  noteListThumb: { width: 56, height: 56, borderRadius: 10, marginRight: 14 },
  noteListDate: { fontSize: 14, fontWeight: '800' as const, color: '#343C4A', marginBottom: 6 },
  noteListTitle: { fontSize: 15, lineHeight: 21, color: '#8F97A5', fontWeight: '600' as const },
  headerActionRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8 },
  headerIconButton: { marginLeft: 0 },
  libraryEditButton: { width: 36, height: 36, borderRadius: 11, marginLeft: 10, backgroundColor: '#EEF2FF', borderWidth: 1, borderColor: '#DCE4FF', alignItems: 'center' as const, justifyContent: 'center' as const },
  libraryDeleteButton: { width: 36, height: 36, borderRadius: 11, marginLeft: 10, backgroundColor: '#FFF1F1', borderWidth: 1, borderColor: '#FFD8D8', alignItems: 'center' as const, justifyContent: 'center' as const },
  mobileDocumentCard: { flexDirection: 'row' as const, alignItems: 'center' as const, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#ECEEF5', borderRadius: 18, paddingHorizontal: 14, paddingVertical: 14, marginBottom: 14, minHeight: 92 },
  mobileDocumentThumb: { width: 56, height: 56, borderRadius: 12, marginRight: 14, alignItems: 'center' as const, justifyContent: 'center' as const, borderWidth: 1 },
  mobileDocumentThumbPdf: { backgroundColor: '#F8FAFF', borderColor: '#DCE4FF' },
  mobileDocumentThumbBlank: { backgroundColor: '#F3F5F8', borderColor: '#E4E8EF' },
  mobileDocumentThumbText: { fontSize: 15, fontWeight: '900' as const, letterSpacing: 0.4 },
  emptyCard: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#ECEEF5', borderRadius: 14, padding: 16, marginTop: 6 },
  emptyTitle: { fontSize: 15, fontWeight: '800' as const, color: '#333B49', marginBottom: 8 },
  emptyBody: { fontSize: 13, lineHeight: 20, color: '#8E95A4', fontWeight: '600' as const },
  mobileActionPanel: { flexDirection: 'row' as const, gap: 8, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#ECEEF5', borderRadius: 14, padding: 8, marginBottom: 14 },
  mobileActionButton: { flex: 1, minHeight: 40, borderRadius: 8, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#F7F9FE', borderWidth: 1, borderColor: '#E6EBF4', paddingHorizontal: 10 },
  mobileActionButtonPrimary: { backgroundColor: C.blue, borderColor: C.blue },
  mobileActionButtonDanger: { backgroundColor: '#FFF1F1', borderColor: '#FFD8D8' },
  mobileActionButtonText: { fontSize: 13, lineHeight: 17, fontWeight: '800' as const, color: '#3A4354', textAlign: 'center' as const },
  mobileActionButtonTextPrimary: { color: '#FFFFFF' },
  mobileActionButtonTextDanger: { color: '#C04B4B' },
  mobileHeaderActions: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6 },
  mobileRecoveryToggle: { minHeight: 42, borderRadius: 12, paddingHorizontal: 14, marginBottom: 12, backgroundColor: '#EEF2FF', borderWidth: 1, borderColor: '#DCE4FF', flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const },
  mobileRecoveryToggleText: { fontSize: 13, fontWeight: '900' as const, color: '#4F68D2' },

  segment: { flexDirection: 'row' as const, backgroundColor: '#F7F8FC', borderRadius: 12, padding: 4, marginBottom: 18 },
  segmentButton: { flex: 1, height: 36, borderRadius: 10, alignItems: 'center' as const, justifyContent: 'center' as const },
  segmentButtonActive: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E8EBF3' },
  segmentText: { fontSize: 14, fontWeight: '700' as const, color: '#B0B6C3' },
  segmentTextActive: { color: '#2D3442' },

  notePreviewCard: { borderRadius: 14, overflow: 'hidden' as const, borderWidth: 1, borderColor: '#ECEEF5', backgroundColor: '#FFFFFF' },
  notePreviewImage: { width: '100%', height: 560 },
  notePreviewHint: { textAlign: 'center' as const, fontSize: 12, color: '#B1B7C3', fontWeight: '600' as const, marginTop: 12 },
  mobileNoteCenterWrap: { flex: 1, minWidth: 0, paddingHorizontal: 4, position: 'relative' as const },
  mobilePageTitleButton: { width: '100%', minWidth: 0, flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'center' as const, paddingHorizontal: 4 },
  mobileDocumentTitle: { flexShrink: 1, maxWidth: '92%', textAlign: 'center' as const },
  mobileDocToolbar: { paddingHorizontal: 10, paddingBottom: 8, gap: 10 },
  mobileDocTools: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, gap: 10 },
  mobileDocToolButton: { width: 38, height: 38, borderRadius: 11, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#F4F6FB', borderWidth: 1, borderColor: '#EEF1F6' },
  workspaceBanner: { width: '100%', borderRadius: 18, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DCE4FF', paddingHorizontal: 14, paddingVertical: 14, marginBottom: 10, shadowColor: '#AAB4C5', shadowOpacity: 0.08, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 2 },
  workspaceBannerEyebrow: { fontSize: 11, fontWeight: '900' as const, color: '#5F79FF', marginBottom: 8, letterSpacing: 0.3 },
  workspaceBannerTitle: { fontSize: 15, lineHeight: 21, color: '#263144', fontWeight: '800' as const, marginBottom: 6 },
  workspaceBannerBody: { fontSize: 13, lineHeight: 18, color: '#72809A', fontWeight: '600' as const },
  workspaceBannerActions: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: 8, marginTop: 12 },
  workspacePrimaryAction: { height: 34, paddingHorizontal: 14, borderRadius: 10, backgroundColor: '#5F79FF', alignItems: 'center' as const, justifyContent: 'center' as const },
  workspacePrimaryActionText: { fontSize: 12, fontWeight: '800' as const, color: '#FFFFFF' },
  workspaceSecondaryAction: { height: 34, paddingHorizontal: 14, borderRadius: 10, backgroundColor: '#EEF2FF', borderWidth: 1, borderColor: '#DCE4FF', alignItems: 'center' as const, justifyContent: 'center' as const },
  workspaceSecondaryActionText: { fontSize: 12, fontWeight: '800' as const, color: '#5169D8' },
  workspaceGhostAction: { height: 34, paddingHorizontal: 14, borderRadius: 10, backgroundColor: '#F5F7FB', borderWidth: 1, borderColor: '#E7EBF3', alignItems: 'center' as const, justifyContent: 'center' as const },
  workspaceGhostActionText: { fontSize: 12, fontWeight: '800' as const, color: '#6F7A8D' },
  workspaceToast: { width: '100%', flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8, borderRadius: 14, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D9E3FF', paddingHorizontal: 14, paddingVertical: 10, marginBottom: 10 },
  workspaceToastText: { flex: 1, fontSize: 12, lineHeight: 16, color: '#47556E', fontWeight: '800' as const },
  workspaceSection: { width: '100%', marginBottom: 8, paddingHorizontal: 10 },
  workspaceSectionHeader: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, paddingHorizontal: 10, marginBottom: 8 },
  workspaceSectionHeaderActions: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8 },
  workspaceSectionTitle: { fontSize: 13, fontWeight: '900' as const, color: '#2D3647' },
  workspaceSectionMeta: { fontSize: 11, fontWeight: '800' as const, color: '#8B96A9' },
  workspaceSectionToggle: { height: 26, paddingHorizontal: 10, borderRadius: 999, backgroundColor: '#EEF2FF', alignItems: 'center' as const, justifyContent: 'center' as const },
  workspaceSectionToggleText: { fontSize: 11, fontWeight: '800' as const, color: '#4F68D2' },
  workspaceCardsRow: { paddingBottom: 8, gap: 10 },
  workspaceCard: { width: 208, minHeight: 110, borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E5EAF3', padding: 14 },
  workspaceInboxCard: { backgroundColor: '#FAFBFE' },
  workspaceCardType: { fontSize: 10, fontWeight: '900' as const, color: '#8D97AA', letterSpacing: 0.6, marginBottom: 8 },
  workspaceCardTitle: { fontSize: 14, lineHeight: 18, color: '#2A3345', fontWeight: '800' as const, marginBottom: 6 },
  workspaceCardBody: { fontSize: 12, lineHeight: 17, color: '#7C879A', fontWeight: '600' as const },
  workspaceCardMeta: { fontSize: 11, lineHeight: 15, color: '#98A2B3', fontWeight: '700' as const, marginTop: 10 },
  workspaceCardAction: { alignSelf: 'flex-start' as const, marginTop: 10, height: 28, paddingHorizontal: 10, borderRadius: 10, backgroundColor: '#F5F7FB', borderWidth: 1, borderColor: '#E5EAF3', alignItems: 'center' as const, justifyContent: 'center' as const },
  workspaceCardActionText: { fontSize: 11, fontWeight: '800' as const, color: '#6B7689' },
  workspaceInlineAction: { alignSelf: 'flex-start' as const, marginTop: 12, paddingHorizontal: 10, height: 30, borderRadius: 10, backgroundColor: '#EEF2FF', alignItems: 'center' as const, justifyContent: 'center' as const },
  workspaceInlineActionText: { fontSize: 11, fontWeight: '800' as const, color: '#4F68D2' },
  workspaceInboxPanel: { width: '100%', borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E6EBF4', paddingHorizontal: 14, paddingVertical: 6 },
  workspaceInboxRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 12, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#EEF2F6' },
  workspaceInboxRowLast: { borderBottomWidth: 0 },
  workspaceInboxRowMeta: { flex: 1 },
  workspaceInboxRowTitle: { fontSize: 14, lineHeight: 18, color: '#263144', fontWeight: '800' as const, marginBottom: 4 },
  workspaceInboxRowBody: { fontSize: 12, lineHeight: 17, color: '#7C879A', fontWeight: '600' as const },
  workspaceInboxRowActions: { alignItems: 'flex-end' as const, gap: 8 },
  workspaceInboxRowButtons: { alignItems: 'flex-end' as const, gap: 6 },
  workspaceInboxStatusPill: { minWidth: 68, height: 24, paddingHorizontal: 10, borderRadius: 999, backgroundColor: '#F4F6FB', alignItems: 'center' as const, justifyContent: 'center' as const },
  workspaceInboxStatusText: { fontSize: 10, fontWeight: '900' as const, color: '#7B8799', letterSpacing: 0.4 },
  workspaceDeleteAction: { alignSelf: 'flex-start' as const, paddingHorizontal: 10, height: 30, borderRadius: 10, backgroundColor: '#FFF1F1', alignItems: 'center' as const, justifyContent: 'center' as const },
  workspaceDeleteActionText: { fontSize: 11, fontWeight: '800' as const, color: '#C04B4B' },
  workspaceEmptyState: { width: '100%', borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E6EBF4', padding: 16, marginBottom: 10 },
  workspaceEmptyTitle: { fontSize: 14, fontWeight: '800' as const, color: '#334055', marginBottom: 6 },
  workspaceDock: {
    position: 'absolute' as const,
    top: 8,
    left: 12,
    width: 300,
    bottom: 8,
    borderRadius: 20,
    backgroundColor: '#F6F8FC',
    borderWidth: 1,
    borderColor: '#E2E8F2',
    shadowColor: '#AAB4C5',
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
    zIndex: 12,
  },
  workspaceDockShifted: { left: 320 },
  workspaceDockTop: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, paddingHorizontal: 14, paddingTop: 14, paddingBottom: 8 },
  workspaceDockClose: { width: 30, height: 30, borderRadius: 99, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#E9EEF6' },
  workspaceDockContent: { paddingHorizontal: 14, paddingBottom: 16, gap: 12 },
  workspaceDockCard: { borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DCE4FF', padding: 12 },
  workspaceDockLabel: { fontSize: 10, fontWeight: '900' as const, color: '#5F79FF', letterSpacing: 0.4, marginBottom: 6 },
  workspaceDockPreviewFrame: { width: '100%', height: 196, borderRadius: 14, marginBottom: 10, backgroundColor: '#EEF2FF', overflow: 'hidden' as const, alignItems: 'center' as const, justifyContent: 'center' as const },
  workspaceDockPreviewImage: { width: '100%', height: '100%' },
  workspaceDockPreviewFallback: { height: 196, borderRadius: 14, marginBottom: 10, backgroundColor: '#EEF2FF', alignItems: 'center' as const, justifyContent: 'center' as const },
  workspaceDockTitle: { fontSize: 15, lineHeight: 20, color: '#263144', fontWeight: '800' as const, marginBottom: 4 },
  workspaceDockMeta: { fontSize: 12, lineHeight: 17, color: '#72809A', fontWeight: '700' as const },
  workspaceDockMetaMuted: { fontSize: 11, lineHeight: 16, color: '#8A93A3', fontWeight: '700' as const, marginTop: 4 },
  workspaceDockActions: { flexDirection: 'row' as const, gap: 8, marginTop: 10 },
  workspaceDockSection: { borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E8ECF4', padding: 10 },
  workspaceDockSectionHeader: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, marginBottom: 8 },
  workspaceDockSectionTitle: { fontSize: 12, fontWeight: '900' as const, color: '#2D3647' },
  workspaceDockSectionMeta: { minWidth: 22, height: 22, borderRadius: 999, backgroundColor: '#EEF2FF', textAlign: 'center' as const, lineHeight: 22, fontSize: 11, fontWeight: '900' as const, color: '#4F68D2' },
  workspaceDockToggle: { height: 26, paddingHorizontal: 10, borderRadius: 999, backgroundColor: '#EEF2FF', alignItems: 'center' as const, justifyContent: 'center' as const },
  workspaceDockToggleText: { fontSize: 11, fontWeight: '800' as const, color: '#4F68D2' },
  workspaceDockRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8, paddingVertical: 8, borderTopWidth: 1, borderTopColor: '#F0F3F8' },
  workspaceDockRowMeta: { flex: 1 },
  workspaceDockRowTitle: { fontSize: 13, lineHeight: 17, color: '#263144', fontWeight: '800' as const, marginBottom: 3 },
  workspaceDockRowBody: { fontSize: 11, lineHeight: 15, color: '#7C879A', fontWeight: '700' as const },
  workspaceDockRowButtons: { alignItems: 'flex-end' as const, gap: 6 },
  workspaceDockInlineAction: { height: 28, paddingHorizontal: 10, borderRadius: 10, backgroundColor: '#EEF2FF', alignItems: 'center' as const, justifyContent: 'center' as const },
  workspaceDockInlineActionText: { fontSize: 11, fontWeight: '800' as const, color: '#4F68D2' },
  workspaceDockDeleteAction: { height: 28, paddingHorizontal: 10, borderRadius: 10, backgroundColor: '#FFF1F1', alignItems: 'center' as const, justifyContent: 'center' as const },
  workspaceDockDeleteActionText: { fontSize: 11, fontWeight: '800' as const, color: '#C04B4B' },
  workspaceDockNoteCard: { borderTopWidth: 1, borderTopColor: '#F0F3F8', paddingTop: 10 },
  workspaceDockNoteCardSpaced: { marginTop: 8 },
  workspaceDockNoteHeader: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, gap: 8, marginBottom: 8 },
  workspaceDockNoteBadge: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6, minHeight: 26, paddingHorizontal: 10, borderRadius: 999, backgroundColor: '#EEF2FF' },
  workspaceDockNoteBadgeText: { fontSize: 11, fontWeight: '800' as const, color: '#4F68D2' },
  workspaceDockNoteMeta: { fontSize: 11, lineHeight: 15, color: '#7C879A', fontWeight: '700' as const, marginBottom: 8 },
  workspaceDockNoteInput: { minHeight: 84, borderRadius: 14, backgroundColor: '#F8FAFD', borderWidth: 1, borderColor: '#E7ECF4', paddingHorizontal: 12, paddingVertical: 10, fontSize: 13, lineHeight: 19, color: '#263144', fontWeight: '700' as const, textAlignVertical: 'top' as const },
  mobilePdfStage: { flex: 1, minHeight: 0, paddingHorizontal: 10, paddingBottom: 8 },
  mobileViewerStage: { paddingHorizontal: 0, paddingBottom: 0 },
  mobileViewerToolbar: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8, paddingHorizontal: 10, paddingBottom: 8 },
  mobileViewerToolButton: { width: 38, height: 38, borderRadius: 11, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#F4F6FB', borderWidth: 1, borderColor: '#EEF1F6' },
  mobileViewerToolButtonActive: { backgroundColor: '#E8EDFF', borderColor: '#DCE4FF' },
  mobileViewerToolButtonDisabled: { opacity: 0.46 },
  mobileViewerPagePill: { flex: 1, minWidth: 0, height: 38, borderRadius: 12, paddingHorizontal: 12, flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'center' as const, gap: 5, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E6EAF2' },
  mobileViewerPagePillText: { flexShrink: 1, fontSize: 12, lineHeight: 16, fontWeight: '900' as const, color: '#445066', textAlign: 'center' as const },
  mobileViewerFallbackCard: { flex: 1, marginHorizontal: 10, marginBottom: 8, borderRadius: 20, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E6EAF2', alignItems: 'center' as const, justifyContent: 'center' as const, paddingHorizontal: 24 },
  mobileViewerFallbackTitle: { fontSize: 17, lineHeight: 23, fontWeight: '900' as const, color: '#263144', marginTop: 12, marginBottom: 8 },
  mobileViewerFallbackBody: { fontSize: 13, lineHeight: 20, fontWeight: '700' as const, color: '#7C879A', textAlign: 'center' as const },
  mobileAiBottomSheet: { marginHorizontal: 10, shadowColor: '#AAB4C5', shadowOpacity: 0.18, shadowRadius: 20, shadowOffset: { width: 0, height: 10 }, elevation: 8 },
  mobileAiBottomSheetBackground: { backgroundColor: '#F6F8FC', borderRadius: 22, borderWidth: 1, borderColor: '#E2E8F2' },
  mobileAiSheet: { position: 'absolute' as const, left: 10, right: 10, bottom: 8, maxHeight: '58%', backgroundColor: '#F6F8FC', borderRadius: 22, borderWidth: 1, borderColor: '#E2E8F2', paddingHorizontal: 16, paddingTop: 10, paddingBottom: 12, shadowColor: '#AAB4C5', shadowOpacity: 0.18, shadowRadius: 20, shadowOffset: { width: 0, height: 10 }, elevation: 8 },
  mobileAiHandle: { alignSelf: 'center' as const, width: 42, height: 5, borderRadius: 99, backgroundColor: '#D8DFEC', marginBottom: 10 },
  mobileAiHeader: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, marginBottom: 12, paddingHorizontal: 16 },
  mobileAiScrollContent: { paddingHorizontal: 16, paddingBottom: 28 },
  summaryTitle: { fontSize: 20, lineHeight: 28, color: C.text, fontWeight: '800' as const, letterSpacing: 0, marginBottom: 10 },
  summaryAccent: { width: 48, height: 4, borderRadius: 99, backgroundColor: C.blue, marginBottom: 16 },
  summaryIntro: { fontSize: 17, lineHeight: 29, color: '#3A4250', fontWeight: '700' as const, marginBottom: 24 },
  summaryLabel: { fontSize: 11, fontWeight: '800' as const, color: '#A0A7B4', marginBottom: 10 },
  summaryBox: { backgroundColor: C.blueSoft, borderRadius: 12, padding: 16, marginBottom: 18 },
  summaryLead: { fontSize: 15, lineHeight: 24, color: '#5B6473', fontWeight: '600' as const },
  summaryRow: { flexDirection: 'row' as const, alignItems: 'flex-start' as const, gap: 10, marginBottom: 14 },
  summaryBar: { width: 4, borderRadius: 99, minHeight: 44, marginTop: 2 },
  summaryBody: { flex: 1, fontSize: 15, lineHeight: 24, color: '#4E5564', fontWeight: '600' as const },
  summarySectionBlock: { paddingTop: 6, paddingBottom: 18, borderBottomWidth: 1, borderBottomColor: '#EEF1F6', marginBottom: 16 },
  summarySectionBlockLast: { borderBottomWidth: 0, marginBottom: 0, paddingBottom: 0 },
  summarySectionTitle: { fontSize: 24, lineHeight: 30, fontWeight: '900' as const, color: '#202735', marginBottom: 12, letterSpacing: 0 },
  summarySectionBody: { flex: 1, fontSize: 16, lineHeight: 27, color: '#3E4655', fontWeight: '600' as const },
  summaryBulletRow: { flexDirection: 'row' as const, alignItems: 'flex-start' as const, gap: 12, marginBottom: 10 },
  summaryBulletDot: { fontSize: 18, lineHeight: 26, color: '#4A5466', fontWeight: '900' as const },
  summaryFormulaBox: { backgroundColor: '#F7F9FC', borderRadius: 16, borderWidth: 1, borderColor: '#E7EBF3', padding: 22 },
  summaryFormulaText: { fontSize: 18, lineHeight: 31, color: '#2E3440', fontWeight: '700' as const, textAlign: 'center' as const, marginBottom: 6 },
  keywordCard: { backgroundColor: '#FFFFFF', borderRadius: 14, borderWidth: 1, borderColor: '#ECEEF5', padding: 16 },
  keywordRow: { flexDirection: 'row' as const, alignItems: 'center' as const, marginBottom: 10 },
  keywordDot: { width: 5, height: 5, borderRadius: 99, backgroundColor: C.blue, marginRight: 10 },
  keywordText: { fontSize: 14, lineHeight: 20, color: '#6A7180', fontWeight: '600' as const },

  desktopNotesTopRow: { flexDirection: 'row' as const, alignItems: 'flex-start' as const, justifyContent: 'space-between' as const, gap: 20, marginBottom: 18 },
  desktopModeSegment: { flexDirection: 'row' as const, backgroundColor: '#EEF1F7', borderRadius: 16, padding: 4, borderWidth: 1, borderColor: '#E1E6F0' },
  desktopModeButton: { minWidth: 92, height: 42, borderRadius: 12, alignItems: 'center' as const, justifyContent: 'center' as const, paddingHorizontal: 18 },
  desktopModeButtonActive: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DCE2EF' },
  desktopModeButtonText: { fontSize: 14, fontWeight: '800' as const, color: '#8D95A6' },
  desktopModeButtonTextActive: { color: '#1F2633' },
  desktopFilters: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: 12, marginBottom: 20 },
  desktopSearch: { flex: 1, minWidth: 220, height: 46, borderRadius: 12, backgroundColor: C.card, borderWidth: 1, borderColor: C.line, flexDirection: 'row' as const, alignItems: 'center' as const, paddingHorizontal: 14 },
  desktopFilterButton: { flexShrink: 0, height: 46, paddingHorizontal: 18, borderRadius: 12, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: C.card, borderWidth: 1, borderColor: C.line },
  desktopFilterButtonText: { fontSize: 14, fontWeight: '700' as const, color: '#394150' },
  desktopPrimaryAction: { backgroundColor: C.blue, borderColor: C.blue },
  desktopPrimaryActionText: { color: '#FFFFFF' },
  recoveryFilterButton: { backgroundColor: '#EEF2FF', borderColor: '#DCE4FF' },
  recoveryPanel: { width: '100%', borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DCE4FF', paddingHorizontal: 14, paddingVertical: 12, marginBottom: 16 },
  recoveryHeader: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, gap: 10, marginBottom: 8 },
  recoveryTitle: { fontSize: 14, fontWeight: '900' as const, color: '#263144' },
  recoveryMeta: { fontSize: 12, fontWeight: '800' as const, color: '#7D8797' },
  recoveryRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 10, minHeight: 48, paddingVertical: 8, borderTopWidth: 1, borderTopColor: '#EEF2F7' },
  recoveryRowMeta: { flex: 1, minWidth: 0 },
  recoveryRowTitle: { fontSize: 13, lineHeight: 18, fontWeight: '900' as const, color: '#2D3647' },
  recoveryRowBody: { fontSize: 12, lineHeight: 17, fontWeight: '700' as const, color: '#7C879A', marginTop: 2 },
  recoveryRestoreButton: { height: 32, paddingHorizontal: 12, borderRadius: 10, backgroundColor: '#EEF2FF', alignItems: 'center' as const, justifyContent: 'center' as const },
  recoveryRestoreButtonText: { fontSize: 12, fontWeight: '900' as const, color: '#4F68D2' },
  webLibraryShell: { flexDirection: 'row' as const, gap: 20, alignItems: 'stretch' as const },
  webLibrarySidebar: { width: 340, gap: 16 },
  webLibrarySearchCard: { borderRadius: 22, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DDE5EF', padding: 16, gap: 12 },
  webLibraryActionRow: { flexDirection: 'row' as const, gap: 10 },
  webLibraryActionStack: { gap: 10 },
  webSubjectList: { borderRadius: 22, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DDE5EF', padding: 14 },
  webSubjectRow: { marginBottom: 10, minHeight: 76 },
  webLibraryContent: { flex: 1, minWidth: 0 },
  webLibraryCard: { borderRadius: 20, borderColor: '#DDE5EF', marginBottom: 16, minHeight: 108 },
  webDocumentCard: { borderBottomWidth: 0, borderRadius: 18, borderWidth: 1, borderColor: '#E8EDF4', paddingHorizontal: 14, paddingVertical: 16, marginBottom: 12 },
  desktopNotesLayout: { flexDirection: 'row' as const, gap: 18 },
  desktopNotesLayoutCompact: { gap: 14 },
  desktopSubjects: { width: 320 },
  desktopSubjectsCompact: { width: 268 },
  desktopDocumentsPanel: { backgroundColor: '#FFFFFF', borderRadius: 20, borderWidth: 1, borderColor: '#E8EBF3', padding: 18 },
  documentListCard: { flexDirection: 'row' as const, alignItems: 'center' as const, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#EEF1F6', paddingVertical: 14, gap: 14 },
  documentListRail: { width: 5, alignSelf: 'stretch' as const, borderRadius: 99 },
  documentThumb: { width: 56, height: 72, borderRadius: 12, alignItems: 'center' as const, justifyContent: 'center' as const, borderWidth: 1, borderColor: '#DEE5F2' },
  documentThumbText: { fontSize: 12, fontWeight: '900' as const, letterSpacing: 0.3 },
  documentTitleRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 10, marginBottom: 6 },
  documentTitle: { flex: 1, fontSize: 16, lineHeight: 22, color: '#3F4756', fontWeight: '700' as const },
  documentTypePill: { paddingHorizontal: 10, height: 24, borderRadius: 999, alignItems: 'center' as const, justifyContent: 'center' as const },
  documentTypeText: { fontSize: 11, fontWeight: '800' as const },
  documentMeta: { fontSize: 12, color: '#98A0AF', fontWeight: '700' as const },

  desktopDetailHeader: { height: 88, backgroundColor: C.card, borderBottomWidth: 1, borderBottomColor: C.line, flexDirection: 'row' as const, alignItems: 'center' as const, paddingHorizontal: 24, gap: 16 },
  desktopDetailHeaderCompact: { height: 78, paddingHorizontal: 18, gap: 12 },
  desktopDetailTitle: { fontSize: 28, fontWeight: '800' as const, color: C.text, marginTop: 6 },
  desktopDetailTitleCompact: { fontSize: 22, marginTop: 4 },
  desktopDetailBody: { flex: 1, flexDirection: 'row' as const },
  desktopDocumentDetailBody: { flex: 1, backgroundColor: '#EFF2F8', paddingHorizontal: 8, paddingVertical: 8, alignItems: 'center' as const },
  desktopImagePanel: { width: '48%', padding: 28, borderRightWidth: 1, borderRightColor: C.line },
  desktopImagePanelCompact: { width: '47%', padding: 18, borderRightWidth: 1, borderBottomWidth: 0, borderBottomColor: C.line },
  desktopDetailImage: { width: '100%', height: 640, borderRadius: 18 },
  desktopDetailImageCompact: { height: 520, borderRadius: 16 },
  desktopSummaryPanel: { flex: 1, backgroundColor: C.card },
  desktopSummaryPanelInner: { padding: 28 },
  desktopSummaryPanelInnerCompact: { padding: 20 },
  documentDetailMetaPill: { height: 34, paddingHorizontal: 14, borderRadius: 999, backgroundColor: '#EEF1F7', alignItems: 'center' as const, justifyContent: 'center' as const },
  documentDetailMetaText: { fontSize: 12, fontWeight: '800' as const, color: '#5D6574' },
  documentRenamePanel: { minHeight: 58, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E6EAF2', flexDirection: 'row' as const, flexWrap: 'wrap' as const, alignItems: 'center' as const, gap: 10, paddingHorizontal: 18, paddingVertical: 10 },
  documentRenameInput: { flex: 1, minWidth: 180, height: 38, borderRadius: 10, backgroundColor: '#F7F9FE', borderWidth: 1, borderColor: '#E4EAF8', paddingHorizontal: 12, fontSize: 14, fontWeight: '800' as const, color: '#263144' },
  documentRenameButton: { height: 38, paddingHorizontal: 14, borderRadius: 10, backgroundColor: '#F5F7FB', borderWidth: 1, borderColor: '#E6EAF2', alignItems: 'center' as const, justifyContent: 'center' as const },
  documentRenameButtonPrimary: { backgroundColor: '#5F79FF', borderColor: '#5F79FF' },
  documentRenameButtonText: { fontSize: 12, fontWeight: '900' as const, color: '#5D6574' },
  documentRenameButtonTextPrimary: { color: '#FFFFFF' },

  inkToolbarWrap: { width: '100%', marginBottom: 8, position: 'relative' as const, zIndex: 30 },
  inkToolbar: { width: '100%', flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'flex-end' as const, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E6EAF2', borderRadius: 16, paddingHorizontal: 14, paddingVertical: 10 },
  documentPageNavigator: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 10, marginRight: 'auto' },
  documentPageNavButton: { width: 34, height: 34, borderRadius: 10, backgroundColor: '#F7F9FE', borderWidth: 1, borderColor: '#E4EAF8', alignItems: 'center' as const, justifyContent: 'center' as const },
  documentPageLabel: { fontSize: 12, fontWeight: '800' as const, color: '#556070' },
  documentPageJump: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 2, minHeight: 34, paddingLeft: 2 },
  documentPageJumpInput: { minWidth: 28, height: 24, paddingHorizontal: 0, fontSize: 12, lineHeight: 16, fontWeight: '800' as const, color: '#556070', textAlign: 'right' as const, backgroundColor: 'transparent', borderWidth: 0, includeFontPadding: false as const },
  documentPageJumpMeta: { fontSize: 12, lineHeight: 16, fontWeight: '800' as const, color: '#556070' },
  documentPageJumpButton: { width: 30, height: 30, borderRadius: 9, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#F7F9FE', borderWidth: 1, borderColor: '#E4EAF8' },
  inkToolbarTools: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 10, marginLeft: 'auto' },
  inkToolCluster: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8 },
  inkToolAnchor: { position: 'relative' as const },
  inkSecondaryCluster: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8 },
  inkPresetGroup: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8, flexWrap: 'wrap' as const },
  inkPopoverAnchor: { position: 'absolute' as const, top: 46, left: 0, zIndex: 40 },
  inkPopoverInline: { width: 264, borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E6EAF2', paddingHorizontal: 14, paddingVertical: 12, gap: 12, shadowColor: '#AAB4C5', shadowOpacity: 0.1, shadowRadius: 14, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  inkPopover: { position: 'absolute' as const, minWidth: 240, borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E6EAF2', paddingHorizontal: 14, paddingVertical: 12, gap: 12, shadowColor: '#AAB4C5', shadowOpacity: 0.1, shadowRadius: 14, shadowOffset: { width: 0, height: 8 }, elevation: 6, zIndex: 40 },
  inkPopoverSection: { gap: 8 },
  inkPopoverLabel: { fontSize: 12, fontWeight: '800' as const, color: '#6A7486' },
  inkColorSwatch: { width: 18, height: 18, borderRadius: 99, borderWidth: 2, borderColor: '#FFFFFF', shadowColor: '#B5BECE', shadowOpacity: 0.16, shadowRadius: 4, shadowOffset: { width: 0, height: 2 }, elevation: 1 },
  inkColorSwatchActive: { borderColor: '#1F2937', transform: [{ scale: 1.08 }] },
  inkWidthButton: { width: 24, height: 24, borderRadius: 99, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#F4F6FB', borderWidth: 1, borderColor: '#E3E8F2' },
  inkWidthButtonActive: { borderColor: '#5A74E8', backgroundColor: '#EEF2FF' },
  inkWidthDot: { backgroundColor: '#334155' },
  mobileInkColorSwatch: { width: 18, height: 18, borderRadius: 99, borderWidth: 2, borderColor: '#FFFFFF' },
  mobileInkColorSwatchActive: { borderColor: '#1F2937', transform: [{ scale: 1.08 }] },
  mobileInkWidthButton: { width: 24, height: 24, borderRadius: 99, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#F4F6FB', borderWidth: 1, borderColor: '#E3E8F2' },
  mobileInkWidthButtonActive: { borderColor: '#5A74E8', backgroundColor: '#EEF2FF' },
  mobileInkWidthDot: { backgroundColor: '#334155' },
  aiPanel: { position: 'absolute' as const, top: 8, bottom: 8, left: 8, width: 300, borderRadius: 20, backgroundColor: '#F6F8FC', padding: 18, borderWidth: 1, borderColor: '#E2E8F2', shadowColor: '#AAB4C5', shadowOpacity: 0.18, shadowRadius: 20, shadowOffset: { width: 0, height: 10 }, elevation: 6, zIndex: 20 },
  aiPanelHeader: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, marginBottom: 8 },
  aiPanelScroll: { flex: 1 },
  aiPanelScrollContent: { paddingBottom: 18 },
  aiPanelClose: { width: 30, height: 30, borderRadius: 99, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#E9EEF6' },
  aiPanelSubtitle: { fontSize: 13, lineHeight: 18, color: '#7E8798', fontWeight: '700' as const, marginBottom: 18 },
  aiStateCard: { borderRadius: 16, backgroundColor: '#FFFFFF', padding: 14, marginBottom: 16, borderWidth: 1, borderColor: '#E4E9F2' },
  aiStateTitle: { fontSize: 12, fontWeight: '800' as const, color: '#8D96A6', marginBottom: 8 },
  aiStateBody: { fontSize: 14, lineHeight: 20, color: '#243047', fontWeight: '700' as const },
  aiSectionLabel: { fontSize: 11, fontWeight: '800' as const, color: '#8A93A3', marginBottom: 8 },
  aiSuggestionChip: { borderRadius: 14, borderWidth: 1, borderColor: '#E4E9F2', backgroundColor: '#FFFFFF', paddingHorizontal: 12, paddingVertical: 10, marginBottom: 8 },
  aiSuggestionText: { fontSize: 13, lineHeight: 18, color: '#31405B', fontWeight: '700' as const },
  aiInputShell: { borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E4E9F2', paddingHorizontal: 12, paddingVertical: 10, marginBottom: 16 },
  aiInput: { minHeight: 96, color: '#243047', fontSize: 14, lineHeight: 20, fontWeight: '600' as const, textAlignVertical: 'top' as const },
  aiActionRow: { flexDirection: 'row' as const, gap: 8, marginBottom: 12 },
  aiPrimaryButton: { flex: 1, minHeight: 38, borderRadius: 12, backgroundColor: '#5F79FF', alignItems: 'center' as const, justifyContent: 'center' as const, paddingHorizontal: 12 },
  aiPrimaryButtonText: { fontSize: 13, fontWeight: '900' as const, color: '#FFFFFF' },
  aiSecondaryButton: { flex: 1, minHeight: 38, borderRadius: 12, backgroundColor: '#EEF2FF', borderWidth: 1, borderColor: '#DCE4FF', alignItems: 'center' as const, justifyContent: 'center' as const, paddingHorizontal: 12 },
  aiSecondaryButtonDisabled: { backgroundColor: '#F5F7FB', borderColor: '#E8ECF4' },
  aiSecondaryButtonText: { fontSize: 12, lineHeight: 16, fontWeight: '900' as const, color: '#5169D8', textAlign: 'center' as const },
  aiSecondaryButtonTextDisabled: { color: '#A8B0BF' },
  aiErrorText: { fontSize: 12, lineHeight: 17, fontWeight: '700' as const, color: '#C35A5A', marginBottom: 12 },
  aiResponseCard: { borderRadius: 16, backgroundColor: '#FFFFFF', padding: 14, borderWidth: 1, borderColor: '#E4E9F2' },
  aiResponseTitle: { fontSize: 12, fontWeight: '800' as const, color: '#8D96A6', marginBottom: 8 },
  aiQuestionPill: { alignSelf: 'flex-start' as const, borderRadius: 999, backgroundColor: '#F3F6FC', borderWidth: 1, borderColor: '#E3E9F4', paddingHorizontal: 10, paddingVertical: 6, marginBottom: 10 },
  aiQuestionPillText: { fontSize: 12, lineHeight: 16, color: '#4E5C76', fontWeight: '700' as const },
  aiResponseSection: { marginBottom: 14 },
  aiResponseSectionLast: { marginBottom: 0 },
  aiResponseSectionTitle: { fontSize: 15, lineHeight: 20, color: '#2F3A4E', fontWeight: '800' as const, marginBottom: 6 },
  aiResponseBody: { fontSize: 13, lineHeight: 19, color: '#42506A', fontWeight: '600' as const },
  inkToolButton: { width: 38, height: 38, borderRadius: 11, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#F4F6FB', borderWidth: 1, borderColor: '#EEF1F6' },
  inkToolButtonActive: { backgroundColor: '#E8EDFF', borderColor: '#DCE4FF' },
  inkToolButtonPopoverOpen: { backgroundColor: '#EEF2FF', borderColor: '#DCE4FF' },
  inkToolButtonText: { fontSize: 13, fontWeight: '800' as const, color: '#6B7280' },
  inkToolButtonTextActive: { color: C.blue },
  inkToolbarDivider: { width: 1, alignSelf: 'stretch' as const, backgroundColor: '#EEF1F6' },
  inkActionButton: { width: 38, height: 38, borderRadius: 11, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#F8FAFD', borderWidth: 1, borderColor: '#EEF1F6' },
  workspaceDockButton: { position: 'relative' as const, backgroundColor: '#F7F9FE', borderColor: '#E4EAF8' },
  workspaceDockButtonActive: { backgroundColor: '#EEF1FD', borderColor: '#D8E0FB' },
  workspaceDockBadge: { position: 'absolute' as const, top: 8, right: 8, width: 7, height: 7, borderRadius: 99, backgroundColor: '#5F79FF' },
  aiIconButton: { backgroundColor: '#F7F8FE', borderColor: '#E7EBFA' },
  aiIconButtonActive: { backgroundColor: '#EEF1FD', borderColor: '#D8E0FB' },
  webWorkspaceShell: { flexDirection: 'row' as const, gap: 18, alignItems: 'stretch' as const },
  webWorkspaceRail: { width: 260, gap: 14 },
  webWorkspaceBack: { height: 42, borderRadius: 14, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DDE5EF', alignItems: 'center' as const, justifyContent: 'center' as const },
  webWorkspaceBackText: { fontSize: 13, fontWeight: '800' as const, color: '#31405B' },
  webWorkspaceRailCard: { borderRadius: 22, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DDE5EF', padding: 16 },
  webWorkspaceRailEyebrow: { fontSize: 10, fontWeight: '900' as const, letterSpacing: 0.9, color: '#8E99AB', marginBottom: 10 },
  webWorkspaceRailTitle: { fontSize: 18, lineHeight: 24, fontWeight: '900' as const, color: '#213044', marginBottom: 6 },
  webWorkspaceRailBody: { fontSize: 13, lineHeight: 19, fontWeight: '600' as const, color: '#6B7A8F' },
  webWorkspaceRailAction: { minHeight: 40, borderRadius: 12, backgroundColor: '#F7F9FC', borderWidth: 1, borderColor: '#E7EDF5', paddingHorizontal: 12, alignItems: 'center' as const, justifyContent: 'center' as const, marginBottom: 8 },
  webWorkspaceRailActionText: { fontSize: 13, fontWeight: '800' as const, color: '#3D4C61' },
  webWorkspaceMiniRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 10, paddingVertical: 10, borderTopWidth: 1, borderTopColor: '#EEF2F7' },
  webWorkspaceMiniTitle: { fontSize: 13, lineHeight: 18, fontWeight: '800' as const, color: '#2D3A4D' },
  webWorkspaceMiniMeta: { fontSize: 12, lineHeight: 16, fontWeight: '600' as const, color: '#7A879B', marginTop: 2 },
  webWorkspaceMain: { flex: 1, minWidth: 0 },
  webWorkspaceDocument: { flex: 1, minHeight: 760 },
  webWorkspaceAside: { width: 340, gap: 14 },
  webWorkspaceAsideCard: { borderRadius: 22, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DDE5EF', padding: 16 },
  webWorkspaceAsideHeader: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, marginBottom: 12 },
  webWorkspaceAsideTitle: { fontSize: 16, fontWeight: '900' as const, color: '#243247' },
  webPdfToolbar: { width: '100%', flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, paddingHorizontal: 16, paddingTop: 14, paddingBottom: 10, borderBottomWidth: 1, borderBottomColor: '#EEF2F7' },
  webPdfToolbarLabel: { fontSize: 10, fontWeight: '900' as const, letterSpacing: 0.8, color: '#8D97AA', marginBottom: 4 },
  webPdfToolbarMeta: { fontSize: 13, fontWeight: '800' as const, color: '#304056' },
  webPdfToolbarButton: { height: 34, paddingHorizontal: 14, borderRadius: 10, borderWidth: 1, borderColor: '#DCE5F0', backgroundColor: '#FFFFFF', alignItems: 'center' as const, justifyContent: 'center' as const },
  webPdfToolbarButtonText: { fontSize: 12, fontWeight: '800' as const, color: '#31405B' },
  pdfLoadingStage: { flex: 1, borderRadius: 20, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E6EAF2', alignItems: 'center' as const, justifyContent: 'center' as const },
  pdfLoadingText: { fontSize: 15, fontWeight: '700' as const, color: '#7D8593' },
  pdfViewerCard: { flex: 1, width: '100%', borderRadius: 20, overflow: 'hidden' as const, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E6EAF2', alignItems: 'center' as const, paddingVertical: 4, position: 'relative' as const },
  generatedPageCard: { flex: 1, width: '100%', borderRadius: 20, backgroundColor: '#E9EEF6', overflow: 'hidden' as const, alignItems: 'center' as const, justifyContent: 'center' as const, padding: 18 },
  generatedPageSheet: { width: '100%', maxWidth: 1180, flex: 1, borderRadius: 22, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DEE6F2', shadowColor: '#AAB4C5', shadowOpacity: 0.12, shadowRadius: 18, shadowOffset: { width: 0, height: 10 }, elevation: 4 },
  generatedPageContent: { flex: 1, paddingHorizontal: 18, paddingTop: 12, paddingBottom: 18 },
  generatedPageHeader: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'flex-end' as const, marginBottom: 10 },
  generatedPageDeleteButton: { height: 30, paddingHorizontal: 12, borderRadius: 999, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E6EAF2', alignItems: 'center' as const, justifyContent: 'center' as const },
  generatedPageDeleteText: { fontSize: 12, fontWeight: '800' as const, color: '#C04B4B' },
  generatedPageLoading: { minHeight: 520, borderRadius: 26, backgroundColor: '#FBF8F2', borderWidth: 1, borderColor: '#E9E1D4', alignItems: 'center' as const, justifyContent: 'center' as const, paddingHorizontal: 24 },
  generatedPageLoadingTitle: { fontSize: 18, lineHeight: 24, fontWeight: '800' as const, color: '#2D3647', marginTop: 18, marginBottom: 10 },
  generatedPageLoadingBody: { fontSize: 14, lineHeight: 21, color: '#758098', fontWeight: '600' as const, textAlign: 'center' as const },
  generatedPageLayout: { flex: 1, flexDirection: 'row' as const, gap: 22, alignItems: 'stretch' as const, minHeight: 0 },
  generatedPageImageColumn: { width: '43%', backgroundColor: '#F9FBFF', borderRadius: 22, borderWidth: 1, borderColor: '#E6EAF2', padding: 18 },
  generatedPageImage: { width: '100%', flex: 1, borderRadius: 18, backgroundColor: '#FFFFFF' },
  generatedPageImageFallback: { flex: 1, borderRadius: 18, backgroundColor: '#EEF2FF', alignItems: 'center' as const, justifyContent: 'center' as const },
  generatedPagePaper: { flex: 1, backgroundColor: '#FFFEFC', borderRadius: 22, borderWidth: 1, borderColor: '#E6EAF2' },
  generatedPagePaperContent: { paddingHorizontal: 22, paddingVertical: 20, paddingBottom: 28 },
  generatedSummaryTitle: { fontSize: 17, lineHeight: 23, color: '#2B3446', fontWeight: '800' as const, letterSpacing: 0, marginBottom: 8 },
  generatedSummaryCard: { borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E8ECF4', paddingHorizontal: 16, paddingVertical: 14, marginBottom: 10 },
  generatedSummaryCardSoft: { backgroundColor: '#FAFBFE' },
  generatedSummaryLabel: { fontSize: 10, fontWeight: '900' as const, color: '#98A2B3', marginBottom: 8, letterSpacing: 0.3 },
  generatedSummaryBody: { fontSize: 13, lineHeight: 20, color: '#435066', fontWeight: '700' as const },
  generatedFormulaCallout: { marginTop: 8, borderRadius: 16, backgroundColor: '#F7F9FC', borderWidth: 1, borderColor: '#E7EBF3', padding: 16 },
  pdfStage: { position: 'relative' as const, overflow: 'hidden' as const, borderRadius: 16 },
  pdfViewer: { flex: 1, backgroundColor: '#F4F6FB' },
  inkOverlay: { ...StyleSheet.absoluteFillObject },
  selectionOverlayRect: { position: 'absolute' as const, borderWidth: 2, borderStyle: 'dashed' as const, borderColor: '#4E8DFF', backgroundColor: 'rgba(78, 141, 255, 0.08)', borderRadius: 8 },
  selectionOverlayDraft: { backgroundColor: 'rgba(78, 141, 255, 0.05)' },
  textAnnotationLayer: { ...StyleSheet.absoluteFillObject },
  textAnnotationCard: { position: 'absolute' as const, minHeight: 84, borderRadius: 14, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E7ECF4', paddingTop: 24, paddingHorizontal: 12, paddingBottom: 10, shadowColor: '#AAB4C5', shadowOpacity: 0.14, shadowRadius: 12, shadowOffset: { width: 0, height: 8 }, elevation: 4 },
  textAnnotationDelete: { position: 'absolute' as const, top: 8, right: 8, width: 20, height: 20, borderRadius: 99, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#F5F7FB' },
  textAnnotationInput: { minHeight: 48, fontSize: 13, lineHeight: 18, color: '#263144', fontWeight: '700' as const, textAlignVertical: 'top' as const },
  textAnnotationAnchorRect: { position: 'absolute' as const, borderRadius: 10, backgroundColor: 'rgba(95, 121, 255, 0.08)', borderWidth: 1, borderColor: 'rgba(95, 121, 255, 0.28)' },
  textAnnotationMarker: { position: 'absolute' as const, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 5, minHeight: 24, paddingHorizontal: 8, borderRadius: 999, backgroundColor: '#5F79FF', shadowColor: '#5F79FF', shadowOpacity: 0.18, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
  textAnnotationMarkerText: { fontSize: 10, fontWeight: '900' as const, color: '#FFFFFF' },
  blankNoteCanvasCard: { flex: 1, width: '100%', borderRadius: 20, overflow: 'hidden' as const, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E6EAF2', alignItems: 'center' as const, justifyContent: 'center' as const, paddingVertical: 4 },
  blankNotePage: { position: 'relative' as const, overflow: 'hidden' as const, borderRadius: 18, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DEE5EF', shadowColor: '#9098A8', shadowOpacity: 0.16, shadowRadius: 18, shadowOffset: { width: 0, height: 10 }, elevation: 4 },
  blankNoteRuleLayer: { ...StyleSheet.absoluteFillObject },
  blankNoteRuleLine: { position: 'absolute' as const, left: 34, right: 26, height: 1, backgroundColor: 'transparent' },
};
