import { C } from './shared';

export const profileStyles = {
  loginScreen: { flex: 1, backgroundColor: C.bg, alignItems: 'center' as const, justifyContent: 'center' as const, paddingHorizontal: 20 },
  loginCard: { width: '100%', maxWidth: 420, borderRadius: 18, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#ECEEF5', padding: 22, shadowColor: '#D8DDE8', shadowOpacity: 0.34, shadowRadius: 20, shadowOffset: { width: 0, height: 10 }, elevation: 8 },
  webLoginCard: { maxWidth: 1080, flexDirection: 'row' as const, alignItems: 'stretch' as const, padding: 0, overflow: 'hidden' as const, borderRadius: 28, borderColor: '#DDE6F0' },
  webLoginIntro: { flex: 1, backgroundColor: '#13212F', paddingHorizontal: 34, paddingVertical: 36, justifyContent: 'center' as const },
  webLoginEyebrow: { fontSize: 11, fontWeight: '900' as const, letterSpacing: 1.2, color: '#8CB6FF', marginBottom: 16 },
  webLoginHeadline: { fontSize: 36, lineHeight: 40, fontWeight: '900' as const, color: '#F7FBFF', marginBottom: 14, letterSpacing: 0 },
  webLoginBody: { fontSize: 15, lineHeight: 23, fontWeight: '600' as const, color: 'rgba(226,236,248,0.78)', marginBottom: 24 },
  webLoginFeatureList: { gap: 12 },
  webLoginFeatureRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 10 },
  webLoginFeatureDot: { width: 8, height: 8, borderRadius: 99, backgroundColor: '#8CB6FF' },
  webLoginFeatureText: { fontSize: 14, fontWeight: '700' as const, color: '#E7F0FA' },
  webLoginForm: { width: 420, backgroundColor: '#FFFFFF', padding: 28 },
  loginLogoWrap: { width: 78, height: 78, marginBottom: 16 },
  loginLogoImage: { width: 78, height: 78, borderRadius: 18 },
  loginTitle: { fontSize: 28, lineHeight: 34, fontWeight: '900' as const, color: C.text, marginBottom: 6 },
  loginSubtitle: { fontSize: 14, lineHeight: 20, fontWeight: '700' as const, color: '#7F8897', marginBottom: 24 },
  loginFieldGroup: { marginBottom: 14 },
  loginLabel: { fontSize: 12, fontWeight: '800' as const, color: '#7C8492', marginBottom: 8 },
  loginInput: { height: 48, borderRadius: 8, borderWidth: 1, borderColor: '#E4E8F0', backgroundColor: '#FAFBFD', paddingHorizontal: 14, color: C.text, fontSize: 15, fontWeight: '700' as const },
  loginError: { color: '#F16D6D', fontSize: 13, fontWeight: '800' as const, marginTop: 2, marginBottom: 12 },
  loginButton: { height: 50, borderRadius: 8, backgroundColor: C.blue, alignItems: 'center' as const, justifyContent: 'center' as const, marginTop: 4 },
  loginButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '900' as const },
  loginDividerRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 10, marginTop: 20, marginBottom: 14 },
  loginDividerLine: { flex: 1, height: 1, backgroundColor: '#EEF1F6' },
  loginDividerText: { fontSize: 12, fontWeight: '800' as const, color: '#B0B7C4' },
  socialLoginButton: { height: 48, borderRadius: 8, borderWidth: 1, borderColor: '#E4E8F0', backgroundColor: '#FFFFFF', flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'center' as const, marginBottom: 10, paddingHorizontal: 14 },
  socialLoginMark: { position: 'absolute' as const, left: 14, width: 24, height: 24, borderRadius: 6, alignItems: 'center' as const, justifyContent: 'center' as const },
  socialLoginMarkGoogle: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DADCE0' },
  socialLoginMarkNaver: { backgroundColor: '#03C75A' },
  socialLoginMarkKakao: { backgroundColor: '#FEE500' },
  socialLoginMarkText: { fontSize: 13, fontWeight: '900' as const, color: '#202124' },
  socialLoginMarkKakaoText: { fontSize: 13, fontWeight: '900' as const, color: '#3A1D1D' },
  socialLoginButtonText: { fontSize: 15, fontWeight: '800' as const, color: '#303846' },
  loginHint: { color: '#A2A8B5', fontSize: 12, lineHeight: 17, fontWeight: '700' as const, textAlign: 'center' as const, marginTop: 14 },
  profileCard: { flexDirection: 'row' as const, alignItems: 'center' as const, marginBottom: 18, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#ECEEF5', borderRadius: 14, padding: 14 },
  profileAvatar: { width: 58, height: 58, borderRadius: 99, backgroundColor: '#EFF2FF', alignItems: 'center' as const, justifyContent: 'center' as const, marginRight: 14 },
  profileAvatarText: { color: C.blue, fontSize: 24, fontWeight: '700' as const },
  profileName: { fontSize: 16, fontWeight: '800' as const, color: C.text, marginBottom: 4 },
  profileDept: { fontSize: 12, color: '#A2A8B5', fontWeight: '600' as const, marginBottom: 10 },
  profileStats: { flexDirection: 'row' as const, gap: 14 },
  profileStat: { fontSize: 12, color: '#7F8897', fontWeight: '700' as const },
  profileFeedbackCard: { backgroundColor: '#F7FAFF', borderRadius: 14, borderWidth: 1, borderColor: '#DCE7FF', padding: 14, marginBottom: 18 },
  profileFeedbackTitle: { fontSize: 11, fontWeight: '900' as const, letterSpacing: 0.8, color: '#5B79D8', marginBottom: 6 },
  profileFeedbackBody: { fontSize: 14, lineHeight: 20, fontWeight: '700' as const, color: '#31405B' },
  profileHelpCard: { backgroundColor: '#FFFFFF', borderRadius: 14, borderWidth: 1, borderColor: '#ECEEF5', padding: 16, marginBottom: 18 },
  profileHelpHeader: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, marginBottom: 10 },
  profileHelpTitle: { fontSize: 15, fontWeight: '900' as const, color: '#223247' },
  profileHelpClose: { minHeight: 32, paddingHorizontal: 12, borderRadius: 999, backgroundColor: '#F3F6FB', alignItems: 'center' as const, justifyContent: 'center' as const },
  profileHelpCloseText: { fontSize: 12, fontWeight: '800' as const, color: '#4A5A70' },
  profileHelpBody: { fontSize: 13, lineHeight: 19, fontWeight: '600' as const, color: '#657489', marginBottom: 8 },
  settingsSection: { marginBottom: 18 },
  settingsTitle: { fontSize: 11, fontWeight: '800' as const, color: '#B2B8C5', marginBottom: 8 },
  settingsCard: { backgroundColor: '#FFFFFF', borderRadius: 12, borderWidth: 1, borderColor: '#ECEEF5', overflow: 'hidden' as const },
  settingsRow: { minHeight: 54, paddingHorizontal: 16, flexDirection: 'row' as const, alignItems: 'center' as const },
  settingsRowPressed: { backgroundColor: '#F7F9FD' },
  settingsRowBorder: { borderBottomWidth: 1, borderBottomColor: '#F0F2F7' },
  settingsLabel: { flex: 1, fontSize: 15, fontWeight: '700' as const, color: '#3A4250' },
  settingsLabelDanger: { color: '#C35A5A' },
  settingsValue: { fontSize: 13, color: '#A0A7B4', fontWeight: '700' as const },
  chevron: { fontSize: 18, color: '#B1B8C5', fontWeight: '700' as const },
  logoutButton: { height: 44, borderRadius: 10, alignItems: 'center' as const, justifyContent: 'center' as const, borderWidth: 1, borderColor: '#ECEEF5', backgroundColor: '#FFFFFF', marginTop: 8, marginBottom: 18 },
  logoutButtonText: { color: '#F16D6D', fontSize: 15, fontWeight: '800' as const },
  footerMeta: { textAlign: 'center' as const, color: '#D0D4DD', fontSize: 11, fontWeight: '600' as const, marginBottom: 2 },
  webProfileHero: { minHeight: 170, borderRadius: 24, borderColor: '#DCE5F0', padding: 22, marginBottom: 24 },
  webProfileHeroMeta: { marginLeft: 'auto' as const, alignItems: 'flex-end' as const },
  webProfileHeroLabel: { fontSize: 11, fontWeight: '800' as const, letterSpacing: 0.8, color: '#8190A8', marginBottom: 6 },
  webProfileHeroValue: { fontSize: 18, fontWeight: '900' as const, color: '#223247' },
  webProfileSectionGrid: { flexDirection: 'row' as const, gap: 18, alignItems: 'flex-start' as const },
  webProfileSectionCell: { flex: 1 },
};
