export const scheduleStyles = {
  mobileHero: { flexDirection: 'row' as const, justifyContent: 'space-between' as const, alignItems: 'flex-start' as const, marginBottom: 12, paddingHorizontal: 6, paddingTop: 2 },
  mobileHeroCompact: { marginBottom: 10 },
  mobileCaption: { fontSize: 11, fontWeight: '700' as const, color: '#9AA2B1', marginBottom: 6 },
  mobileCaptionCompact: { marginBottom: 4 },
  heroTitleRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6 },
  heroTitle: { fontSize: 20, fontWeight: '800' as const, color: '#171B24', letterSpacing: 0 },
  heroTitleCompact: { fontSize: 19 },
  heroTitleArrow: { fontSize: 16, color: '#9AA2B1' },
  heroActions: { flexDirection: 'row' as const, gap: 6, marginTop: 1 },
  heroIcon: { width: 32, height: 32, borderRadius: 12, alignItems: 'center' as const, justifyContent: 'center' as const },
  heroIconText: { fontSize: 24, color: '#171B24', fontWeight: '400' as const, lineHeight: 28 },
  gearIcon: { width: 18, height: 18, alignItems: 'center' as const, justifyContent: 'center' as const, position: 'relative' as const },
  gearCenter: { width: 11, height: 11, borderRadius: 99, borderWidth: 1.5, borderColor: '#303846' },
  gearTooth: { position: 'absolute' as const, width: 1.8, height: 4, borderRadius: 99, backgroundColor: '#303846' },
  gearToothTop: { top: 0.1 },
  gearToothBottom: { bottom: 0.1 },
  gearToothLeft: { left: 0.1, transform: [{ rotate: '90deg' }] },
  gearToothRight: { right: 0.1, transform: [{ rotate: '90deg' }] },
  gearToothTopLeft: { top: 1.6, left: 1.6, transform: [{ rotate: '-45deg' }] },
  gearToothTopRight: { top: 1.6, right: 1.6, transform: [{ rotate: '45deg' }] },
  gearToothBottomLeft: { bottom: 1.6, left: 1.6, transform: [{ rotate: '45deg' }] },
  gearToothBottomRight: { bottom: 1.6, right: 1.6, transform: [{ rotate: '-45deg' }] },

  timetableCard: { backgroundColor: '#FFFFFF', borderRadius: 22, borderWidth: 1, borderColor: '#E8EBF3', overflow: 'hidden' as const, shadowColor: '#D9DDEA', shadowOpacity: 0.18, shadowRadius: 18, shadowOffset: { width: 0, height: 8 }, elevation: 3 },
  timetableHeader: { flexDirection: 'row' as const, alignItems: 'center' as const, height: 38, borderBottomWidth: 1, borderBottomColor: '#EEF1F6', backgroundColor: '#FFFFFF' },
  timeColumnSpacer: { width: 34 },
  dayHeaderCell: { flex: 1, alignItems: 'center' as const, justifyContent: 'center' as const },
  dayHeaderText: { fontSize: 12, fontWeight: '700' as const, color: '#6D7483' },
  timetableGrid: { flexDirection: 'row' as const },
  timeColumn: { width: 34 },
  timeCell: { alignItems: 'center' as const, borderBottomWidth: 1, borderBottomColor: '#F2F4F8', paddingTop: 8, backgroundColor: '#FFFFFF' },
  timeText: { fontSize: 10, color: '#B3BAC7', fontWeight: '600' as const },
  dayColumns: { flex: 1, flexDirection: 'row' as const, position: 'relative' as const },
  dayColumn: { flex: 1, position: 'relative' as const, backgroundColor: '#FFFFFF' },
  dayColumnBorder: { borderRightWidth: 1, borderRightColor: '#F2F4F8' },
  slotCell: { borderBottomWidth: 1, borderBottomColor: '#F2F4F8', backgroundColor: '#FFFFFF' },
  classBlock: { position: 'absolute' as const, borderRadius: 10, paddingHorizontal: 6, paddingVertical: 6, justifyContent: 'space-between' as const, overflow: 'hidden' as const },
  classBlockInset: { left: 2, right: 2 },
  classTitle: { fontSize: 10.2, lineHeight: 13, fontWeight: '800' as const, textAlign: 'left' as const },
  classMeta: { marginTop: 2, fontSize: 8, lineHeight: 10, opacity: 0.72, textAlign: 'left' as const, fontWeight: '700' as const },
  nowLineWrap: { position: 'absolute' as const, width: '20%', flexDirection: 'row' as const, alignItems: 'center' as const, paddingHorizontal: 2 },
  nowDot: { width: 7, height: 7, borderRadius: 99, backgroundColor: '#6677FF' },
  nowLine: { flex: 1, height: 2, backgroundColor: '#6677FF' },

  semesterRow: { minHeight: 72, flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, borderBottomWidth: 1, borderBottomColor: '#F1F3F7' },
  semesterTitle: { fontSize: 14, fontWeight: '800' as const, color: '#3B4351', marginBottom: 4 },
  semesterMeta: { fontSize: 12, color: '#A0A7B4', fontWeight: '600' as const },
  chevron: { fontSize: 22, color: '#C0C6D2' },

  desktopBoard: { backgroundColor: '#FFFFFF', borderRadius: 24, borderWidth: 1, borderColor: '#E9ECF3', overflow: 'hidden' as const },
  desktopBoardCompact: { borderRadius: 20 },
  desktopDayHeader: { fontSize: 15, fontWeight: '800' as const, color: '#6D7483' },
  desktopTimeText: { fontSize: 12, color: '#ADB4C2', fontWeight: '700' as const },
  desktopClassBlock: { position: 'absolute' as const, borderRadius: 14, paddingHorizontal: 12, paddingVertical: 14, justifyContent: 'space-between' as const },
  desktopClassBlockCompact: { borderRadius: 12, paddingHorizontal: 10, paddingVertical: 10 },
  desktopClassBlockInset: { left: 6, right: 6 },
  desktopClassTitle: { fontSize: 15, lineHeight: 20, fontWeight: '800' as const, textAlign: 'left' as const },
  desktopClassTitleCompact: { fontSize: 13, lineHeight: 17 },
  desktopClassMeta: { marginTop: 8, fontSize: 12, opacity: 0.7, fontWeight: '700' as const, textAlign: 'left' as const },
  desktopClassMetaCompact: { marginTop: 6, fontSize: 10 },
};
