export const C = {
  bg: '#F7F8FC',
  card: '#FFFFFF',
  text: '#171B24',
  mute: '#98A0AF',
  line: '#E9ECF3',
  blue: '#6677FF',
  blueSoft: '#EEF1FF',
};

export const sharedStyles = {
  safe: { flex: 1, backgroundColor: C.bg },
  app: { flex: 1, backgroundColor: C.bg, paddingBottom: 8 },
  main: { flex: 1 },
  fill: { flex: 1 },
  desktop: { flex: 1, flexDirection: 'row' as const },
  desktopCompact: { backgroundColor: C.bg },
  webDesktop: { padding: 18, gap: 18, backgroundColor: '#EEF3F8' },
  webMainShell: { flex: 1, borderRadius: 28, overflow: 'hidden' as const, backgroundColor: '#F7FAFD', borderWidth: 1, borderColor: '#DDE6F0' },
  webPanelSurface: { flex: 1, backgroundColor: '#F7FAFD' },
  mobilePage: { paddingHorizontal: 14, paddingTop: 6, paddingBottom: 108 },
  mobilePageCompact: { paddingTop: 4, paddingBottom: 24 },
  noteDetailPage: { paddingHorizontal: 14, paddingTop: 8, paddingBottom: 108 },
  desktopPage: { padding: 32, paddingBottom: 48 },
  desktopPageCompact: { padding: 22, paddingBottom: 32 },
  webDesktopPage: { padding: 28, paddingBottom: 36 },

  sidebar: { width: 88, backgroundColor: C.card, borderRightWidth: 1, borderRightColor: C.line, paddingTop: 28, gap: 12, alignItems: 'center' as const },
  sidebarCompact: { width: 74, paddingTop: 22 },
  sidebarButton: { width: 52, height: 52, borderRadius: 16, alignItems: 'center' as const, justifyContent: 'center' as const },
  sidebarButtonActive: { backgroundColor: C.blueSoft },
  webSidebar: { width: 280, borderRightWidth: 0, borderRadius: 28, paddingTop: 24, paddingHorizontal: 18, alignItems: 'stretch' as const, backgroundColor: '#13212F', gap: 10 },
  webSidebarBrand: { paddingHorizontal: 10, paddingTop: 8, paddingBottom: 18, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.08)', marginBottom: 8 },
  webSidebarEyebrow: { fontSize: 11, fontWeight: '900' as const, letterSpacing: 1.2, color: '#8CB6FF', marginBottom: 10 },
  webSidebarTitle: { fontSize: 28, lineHeight: 32, fontWeight: '900' as const, color: '#F7FBFF', marginBottom: 8 },
  webSidebarBody: { fontSize: 13, lineHeight: 19, fontWeight: '600' as const, color: 'rgba(226,236,248,0.74)' },
  webSidebarButton: { width: '100%', height: 72, borderRadius: 18, paddingHorizontal: 16, flexDirection: 'row' as const, justifyContent: 'flex-start' as const, gap: 14, backgroundColor: 'transparent' },
  webSidebarButtonActive: { backgroundColor: 'rgba(115,146,255,0.16)' },
  webSidebarButtonTextWrap: { flex: 1 },
  webSidebarButtonLabel: { fontSize: 15, fontWeight: '800' as const, color: '#D7E2EE', marginBottom: 3 },
  webSidebarButtonLabelActive: { color: '#FFFFFF' },
  webSidebarButtonHint: { fontSize: 12, lineHeight: 16, fontWeight: '600' as const, color: 'rgba(215,226,238,0.64)' },
  webSidebarButtonHintActive: { color: 'rgba(255,255,255,0.78)' },
  webSidebarFoot: { marginTop: 'auto' as const, paddingTop: 16, paddingBottom: 8, paddingHorizontal: 10 },
  webSidebarFootText: { fontSize: 11, fontWeight: '800' as const, color: 'rgba(215,226,238,0.48)', letterSpacing: 0.8 },

  tabbar: {
    flexDirection: 'row' as const,
    marginHorizontal: 14,
    marginBottom: 10,
    paddingHorizontal: 10,
    paddingTop: 7,
    paddingBottom: 7,
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
    borderColor: '#ECEFF5',
    borderRadius: 16,
    shadowColor: '#D8DDE8',
    shadowOpacity: 0.3,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  tabButton: { flex: 1, height: 38, borderRadius: 11, alignItems: 'center' as const, justifyContent: 'center' as const },
  tabButtonActive: { backgroundColor: C.blueSoft },

  iconBase: { width: 24, height: 24, alignItems: 'center' as const, justifyContent: 'center' as const },
  calendarOutline: { width: 17, height: 17, borderWidth: 1.7, borderRadius: 4 },
  calendarLine: { position: 'absolute' as const, top: 5, left: 2, right: 2, height: 1.7, borderRadius: 99 },
  calendarPinLeft: { position: 'absolute' as const, top: -3, left: 3, width: 2.5, height: 5, borderRadius: 99 },
  calendarPinRight: { position: 'absolute' as const, top: -3, right: 3, width: 2.5, height: 5, borderRadius: 99 },
  docOutline: { width: 14, height: 18, borderWidth: 1.7, borderRadius: 4 },
  docLineLong: { position: 'absolute' as const, top: 5, left: 2.5, right: 2.5, height: 1.7, borderRadius: 99 },
  docLineShort: { position: 'absolute' as const, top: 10, left: 2.5, width: 6, height: 1.7, borderRadius: 99 },
  cameraOutline: { width: 18, height: 13, borderWidth: 1.7, borderRadius: 4 },
  cameraLens: { position: 'absolute' as const, top: 3, left: 5.5, width: 5.5, height: 5.5, borderWidth: 1.7, borderRadius: 99 },
  cameraHead: { position: 'absolute' as const, top: -3, left: 3, width: 5, height: 3 },
  personHead: { width: 7, height: 7, borderWidth: 1.7, borderRadius: 99, marginBottom: 2 },
  personBody: { width: 14, height: 8, borderWidth: 1.7, borderTopLeftRadius: 9, borderTopRightRadius: 9, borderBottomWidth: 0 },

  centerTopBar: { height: 40, flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, marginBottom: 14 },
  navIcon: { width: 32, height: 32, alignItems: 'center' as const, justifyContent: 'center' as const },
  navIconText: { fontSize: 22, fontWeight: '700' as const, color: C.text },
  centerTopTitle: { fontSize: 18, fontWeight: '700' as const, color: C.text },
  noteCenterWrap: { alignItems: 'center' as const },
  noteCenterTitle: { fontSize: 18, fontWeight: '700' as const, color: C.text },
  noteCenterDate: { fontSize: 13, fontWeight: '600' as const, color: '#A3AAB7', marginTop: 2 },

  pageTitle: { fontSize: 24, fontWeight: '800' as const, color: C.text, letterSpacing: -0.8, marginBottom: 14 },
  searchBox: { height: 40, borderRadius: 12, backgroundColor: '#FAFBFD', borderWidth: 1, borderColor: '#F0F2F7', flexDirection: 'row' as const, alignItems: 'center' as const, paddingHorizontal: 12, marginBottom: 16 },
  searchIcon: { fontSize: 14, color: '#C3C8D5', marginRight: 8 },
  searchInput: { flex: 1, fontSize: 14, color: C.text, paddingVertical: 0 },

  desktopHeader: { marginBottom: 20 },
  desktopHeaderCompact: { marginBottom: 16 },
  desktopCaption: { fontSize: 13, fontWeight: '800' as const, color: '#8F96A5', marginBottom: 8 },
  desktopTitle: { fontSize: 34, lineHeight: 40, fontWeight: '800' as const, color: C.text, letterSpacing: -1 },
  desktopTitleCompact: { fontSize: 30, lineHeight: 36 },
  webPageHeader: { flexDirection: 'row' as const, alignItems: 'flex-end' as const, justifyContent: 'space-between' as const, marginBottom: 24 },
  webPageHeaderMeta: { maxWidth: 520 },
  webPageEyebrow: { fontSize: 11, fontWeight: '900' as const, letterSpacing: 1, color: '#5B79D8', marginBottom: 8 },
  webPageTitle: { fontSize: 36, lineHeight: 40, fontWeight: '900' as const, color: '#182433', marginBottom: 8, letterSpacing: -1.2 },
  webPageBody: { fontSize: 14, lineHeight: 21, fontWeight: '600' as const, color: '#607085' },
  webHeaderBadgeRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 10 },
  webHeaderBadge: { height: 36, paddingHorizontal: 14, borderRadius: 999, borderWidth: 1, borderColor: '#D7E3F1', backgroundColor: '#FFFFFF', alignItems: 'center' as const, justifyContent: 'center' as const },
  webHeaderBadgeText: { fontSize: 12, fontWeight: '800' as const, color: '#425166' },
  appOverlay: { position: 'absolute' as const, top: 10, left: 0, right: 0, zIndex: 50, elevation: 50, pointerEvents: 'box-none' as const },
  appBannerWrap: { paddingHorizontal: 14, alignItems: 'center' as const },
  appBanner: {
    width: '100%',
    maxWidth: 680,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderWidth: 1,
    borderColor: '#DEE5F6',
    paddingHorizontal: 12,
    paddingVertical: 12,
    shadowColor: '#9FAED6',
    shadowOpacity: 0.24,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
  },
  appBannerThumb: { width: 48, height: 48, borderRadius: 12 },
  appBannerMain: { flex: 1 },
  appBannerClose: { width: 28, height: 28, borderRadius: 999, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: '#F4F6FB' },
  appBannerCloseText: { fontSize: 14, fontWeight: '800' as const, color: '#657088' },
  appBannerTitle: { fontSize: 14, lineHeight: 19, fontWeight: '800' as const, color: C.text, marginBottom: 3 },
  appBannerBody: { fontSize: 12, lineHeight: 16, fontWeight: '700' as const, color: '#6E788B' },
  appBannerActions: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8 },
  appBannerPrimaryButton: { height: 34, paddingHorizontal: 14, borderRadius: 10, backgroundColor: C.blue, alignItems: 'center' as const, justifyContent: 'center' as const },
  appBannerPrimaryText: { fontSize: 13, fontWeight: '800' as const, color: '#FFFFFF' },
};
